### ISSUE TITLE
Bag Of Golf

### ISSUE THREAD

**Issue by Xorgone** [Rocologo/BagOfGold#10]
When right clicking the Banker created through Bagof gold, there is a typo. It reads exactly "Hi, I am the BagOfGolf Banker, please choose an action...:

It should be BagOfGold. :p

Also, I tested the plugin again on my server and it works great now! Thanks for your hard work.

**Comment by Xorgone** [comment]
https://github.com/Rocologo/BagOfGold/issues/3

I was from this thread but didn't know if I should re-open a new issue because its unrelated.

**Comment by Rocologo** [comment]
I prefer that you open new tickets :when you find new bugs.

The spelling bug is corrected in next release. Nut you will need to correct the bug in your lang file or refresh the file by deleting the lang file completely. (Depending on if you have made other changes).
