### ISSUE TITLE
[Feature Request] PlaceholderAPI support

### ISSUE THREAD

**Issue by PaisWillie** [Rocologo/BagOfGold#101]
Could you please add PAPI support, so I can use a placeholder to show players how much money they have in their bank?

You can upload placeholders [here](https://api.extendedclip.com/all/).

**Comment by Rocologo** [comment]
You already have PlaceholderAPI support



Sendt fra Samsung Galaxy S10+



-------- Oprindelig besked --------
Fra: Willie π <notifications@github.com>
Dato: 09.05.2020 19.40 (GMT+01:00)
Til: Rocologo/BagOfGold <BagOfGold@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Emne: [Rocologo/BagOfGold] [Feature Request] PlaceholderAPI support (#101)


Could you please add PAPI support, so I can use a placeholder to show players how much money they have in their bank?

You can upload placeholders here<https://api.extendedclip.com/all/>.

**Comment by PaisWillie** [comment]
I mean a placeholder like %bagofgold_bank_balance% so I can use it in FeatherBoard to show players how much money they have in their bank

**Comment by Rocologo** [comment]
%bagofgold_bank_balance%
and
 %bagofgold_balance%

should be working

**Comment by Rocologo** [comment]
It seems that I have forgotten to document the placeholders added on the homepage, but they are added now.

https://www.spigotmc.org/resources/bagofgold.49332/

I have not testet the placeholders myself for a very long time, so let me know if you have problems.

**Comment by PaisWillie** [comment]
Both %bagofgold_balance% and %bagofgold_bank_balance% are working perfectly with Featherboard. Thanks!
