### ISSUE TITLE
Bank clearing when players log out and back in. 

### ISSUE THREAD

**Issue by saywhat2365** [Rocologo/BagOfGold#104]
I haven't been able to reproduce but it had happened to 6 players so far. We are using mysql for storage. They have money in their bank and they log off for about an hour and come back and it's empty. If you need more information let me know. If you think it's sql I can switch to sqlite and test that.

**Comment by Rocologo** [comment]
I use MySQL myself and I dont think it will help switching to sqlite. The only thing which will help that find whats trigger this issue.

**Comment by Rocologo** [comment]
And please upgrade to newest version

**Comment by saywhat2365** [comment]
It seems to happen when the server restarts.  I just updated to the latest version so I'll see if this works.  I also noticed another issue.  The NPC banker doesn't have any options it's just blank.  https://gyazo.com/01730d46e4eadf41b787ece04e08bdc9

**Comment by Rocologo** [comment]
I cant reproduce this bug. The bank balance is not cleared on any of my servers, so you need to enable debug using "/bag debug" 

Aboit the NPC: What options have you entered in the config.yml?
