### ISSUE TITLE
Major money dupe bug

### ISSUE THREAD

**Issue by Nullsify** [Rocologo/BagOfGold#106]
We have discovered a major bug in the plugin.
There seems to be a way to duplicate multiple max stack money using only a few bag of golds.
Steps on recreating the bug:
1. Get any amount of Bagofgold.
2. Right click the bagofgold and divide them into a small account.
3. Stack the small amounts of bag of gold by shift-left-clicking them into 1 stack.
4. Once you have a lot bag of golds into 1 stack. (like in the video) Get one of the bagofgold from the stack and proceed to LEFT CLICK it onto the stack.
5. This makes ALL of the bagofgold into the amount you add into it. (In the video, you have 16 625 bagofgold, once you left click it into the stack, they ALL become 1250 bagofgold) This can snowball quickly and make you millions, basically breaking the economy.
https://youtu.be/Lp1gEEiJOAg
We were using 3.0.0

**Comment by Rocologo** [comment]
I fixed a money dupe i 3.0.1 could you please test newest version?



Sendt fra Samsung Galaxy S10+



-------- Oprindelig besked --------
Fra: Nullsify <notifications@github.com>
Dato: 19.07.2020 21.58 (GMT+01:00)
Til: Rocologo/BagOfGold <BagOfGold@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Emne: [Rocologo/BagOfGold] Major money dupe bug (#106)


We have discovered a major bug in the plugin.
There seems to be a way to duplicate multiple max stack money using only a few bag of golds.
Steps on recreating the bug:

  1.  Get any amount of Bagofgold.
  2.  Right click the bagofgold and divide them into a small account.
  3.  Stack the small amounts of bag of gold by shift-left-clicking them into 1 stack.
  4.  Once you have a lot bag of golds into 1 stack. (like in the video) Get one of the bagofgold from the stack and proceed to LEFT CLICK it onto the stack.
  5.  This makes ALL of the bagofgold into the amount you add into it. (In the video, you have 16 625 bagofgold, once you left click it into the stack, they ALL become 1250 bagofgold) This can snowball quickly and make you millions, basically breaking the economy.
https://youtu.be/Lp1gEEiJOAg
We were using 3.0.0

**Comment by Nullsify** [comment]
seems that it is fixed, nice! but all of the items have this weird lore again
https://cdn.discordapp.com/attachments/725238963786219580/734692779644420162/unknown.png
https://cdn.discordapp.com/attachments/725238963786219580/734692824154505226/unknown.png

**Comment by Rocologo** [comment]
I have fund some bugs, which is fixed in V3.0.3

You remove the "strange" lores by install ProtocolLib
