### ISSUE TITLE
Command for 'all'

### ISSUE THREAD

**Issue by jackdebates** [Rocologo/BagOfGold#109]
Any possibility adding an 'all' command to this: */money bag give playername 10 (admin)*

So you can replace 'playername' with 'all'. 

Would be so useful. Cheers!

**Comment by jackdebates** [comment]
Thanks that's great! I tried the newest build and the stable build available on Spigot. Neither worked for me. Just got message 'internal error occured'. The plugin seems to be installed fine as well.

Could you also add /bagofgold bag **TAKE** * 10 (admin - take all online players 10)

Thanks :)

**Comment by Rocologo** [comment]
Please show me the error text from the server console when this happens?

**Comment by jackdebates** [comment]
https://pastebin.com/0mPDHrBs

**Comment by jackdebates** [comment]
@Rocologo so basically I really want the ability to give AND take money from all players' bank accounts.

**Comment by jackdebates** [comment]
Not their on-hand cash. Their **bank accounts**!

**Comment by jackdebates** [comment]
How'd you go with it man? Or haven't got to it yet

**Comment by Rocologo** [comment]
Why do you want to take money from ALL bank accounts?
