### ISSUE TITLE
Bag of gold in inv and no balance

### ISSUE THREAD

**Issue by CampingSteve** [Rocologo/BagOfGold#11]
![2018-01-15 1](https://user-images.githubusercontent.com/35006599/34960214-d94a8640-fa31-11e7-96fc-a548f0355d7f.png)

**Comment by CampingSteve** [comment]
BagofGold version 1.0,2 and Mobhunting 5.3.6 work fine
something has changed in the new versions

**Comment by CampingSteve** [comment]
i'm not doing anything in the lastest versions to cause an issue.....just logging of and back on again causes the issue......also getting BagofGold Head no owner and bagofgold's head in inv

**Comment by Rocologo** [comment]
Sorry. I'm not able to understand what the problems by just looking at a picture. 

I assume that the 5000 Bagofgold has broken, somehow. Just login and logoff does not break the bagofgold, so you have to help me finding out whats break the Value of the bag.

**Comment by CampingSteve** [comment]
not sure what it is...I did /eco give cam 5000...then dc'd....stopped the server....restarted server and rejoined.
I was using BagofGold 1.0.3 and Mobhunting 5.4.1

**Comment by CampingSteve** [comment]
gone back to an older version 1.0.2 bog and mh 5.3.6........those work flawlessly together.  Not sure whats been changed.

**Comment by Rocologo** [comment]
I will try to do the same :-) just make sure ...

**Comment by Rocologo** [comment]
Do you use PerWorldInventory? Have you updated to the new version 1.11.2 ?

**Comment by CampingSteve** [comment]
just these....ignore your plugin versions...I can put the new versions back on
![2018-01-15 2](https://user-images.githubusercontent.com/35006599/34961996-c54bb440-fa39-11e7-8d4a-04b3a03915be.png)

**Comment by CampingSteve** [comment]
I am taking down Sol Kingdoms soon, as nobody plays it anymore and replacing with this....as I prefer hard survival....hence why I love your plugin.

**Comment by Rocologo** [comment]
Wiat I found a bug I will make a new snapshot for you to test. In 15 min or so :-)

**Comment by CampingSteve** [comment]
ok I will run with /mh debug on again
and show you the Console

**Comment by Rocologo** [comment]
Please test build 49
https://fractal.lindegaard.one:8181/job/BagOfGold/

And 
Build 555
https://fractal.lindegaard.one:8181/job/MobHunting/

It seems to work on my test server now.

**Comment by Rocologo** [comment]
I though I had tested that before. Changing the balance and the stop and start the server, to make sure changes was saved.

Have you have any problems with playerheads after testing 5.4.1?

**Comment by CampingSteve** [comment]
ok adding them now

**Comment by CampingSteve** [comment]
only when I get BagOfGolds(s) head in my inv...then I can put the head on

**Comment by Rocologo** [comment]
Yes. I can deny you to put the bag in the head slot, but it should be removed to your inventory as sooon as you closes the inventory?

**Comment by CampingSteve** [comment]
![2018-01-15 3](https://user-images.githubusercontent.com/35006599/34962848-67123d50-fa3d-11e7-950f-1bcce9786cae.png)
plugins loaded

**Comment by Rocologo** [comment]
If it works I will make a release - but I have to go to bed in 12 min :-)

**Comment by CampingSteve** [comment]
![2018-01-15 4](https://user-images.githubusercontent.com/35006599/34962910-bd44837c-fa3d-11e7-80d7-90173855dac8.png)

I gave myself £3000 using /eco give but after restarting it has reset my balance to £0

**Comment by CampingSteve** [comment]
I'll do it again just to make sure its repeatable

**Comment by Rocologo** [comment]
please notice if you get this block when you shutdown

 [BagOfGold][Debug] Shutdown StoreManager
[22:51:03 INFO]: [BagOfGold][Debug] Flushing waiting 1 data to database...
[22:51:03 INFO]: [BagOfGold][Debug] PlayerSettings saved.
[22:51:04 INFO]: [BagOfGold][Debug] mTaskThread.state=WAITING
[22:51:04 INFO]: [BagOfGold][Debug] mStoreThread.state=TIMED_WAITING
[22:51:04 INFO]: [BagOfGold][Debug] Interupting mStoreThread
[22:51:04 INFO]: [BagOfGold][Debug] mTaskThread.state=WAITING
[22:51:04 INFO]: [BagOfGold][Debug] StoreThread was interrupted
[22:51:04 INFO]: [BagOfGold][Debug] Interupting mTaskThread
[22:51:04 INFO]: [BagOfGold][Debug] Shutdown Store
[22:51:04 INFO]: [BagOfGold][Debug]  TaskThread was interrupted
[22:51:04 INFO]: [BagOfGold] Closing database connection.
[22:51:04 INFO]: [BagOfGold][Debug] BagOfGold disabled.
[22:51:04 INFO]:

This part
[22:51:03 INFO]: [BagOfGold][Debug] Flushing waiting 1 data to database...
[22:51:03 INFO]: [BagOfGold][Debug] PlayerSettings saved.
Tell that it saved the changes you just made (1 data = 1 change)

**Comment by Rocologo** [comment]
I have to go to bed now, I have a very important meeting tomorrow... 

Fortunately this is not a big problem, because you usually dont shutdown the server very often... :-) only test servers...

**Comment by CampingSteve** [comment]
its wiped my balance again after restart

**Comment by Rocologo** [comment]
i have tried 5 times and after I made the change I cant replicate the bug anymore...

**Comment by Rocologo** [comment]
strange... we must do something differently ????

**Comment by CampingSteve** [comment]
dc'd and relogged....balance saved

**Comment by CampingSteve** [comment]
dc'd then shut server down balance not saved

**Comment by CampingSteve** [comment]
disconnected from server

**Comment by Rocologo** [comment]
ahh.... i did not disconnect. I did just shutdown the server... I will test it your way tomorrow...

**Comment by CampingSteve** [comment]
anyway its late and you have a busy day...will go back to 5.3.6 and 1.0.2 for now

**Comment by CampingSteve** [comment]
its working....after I removed the plugin dirs and let it regen the files....maybe someone will have the same problem when updating versions....but i'm not sure.

**Comment by Rocologo** [comment]
strange... I will investigate a bit more tomorrow before I make a release :-)

**Comment by Rocologo** [comment]
I have released the new versions now :-)

**Comment by CampingSteve** [comment]
awesome just added them to my new survival server ;) 
136.243.179.186:60202
