### ISSUE TITLE
PlayerJoinEvent

### ISSUE THREAD

**Issue by Raisy1** [Rocologo/BagOfGold#113]
I have an issue when i join the server: https://imgur.com/a/BPgKAZm 
i installed protocollib, essentials and vault 
im using paperspigot 1.16.3

**Comment by Rocologo** [comment]
I need ty see the full error text from the server console not screenshots.

It could be that you have made an error in config.yml but im not sure yet.

**Comment by HakanYT2006** [comment]
no i dont touch config.yml

**Comment by HakanYT2006** [comment]
do you have discord?

**Comment by HakanYT2006** [comment]
https://sourceb.in/d2c1716811 here are the log

**Comment by HakanYT2006** [comment]
help me

**Comment by Rocologo** [comment]
Do you still see this error?
