### ISSUE TITLE
Command request

### ISSUE THREAD

**Issue by jackdebates** [Rocologo/BagOfGold#115]
Some questions/requests:

Please add /bagofgold bag give * 10 (admin - give all online players 10)
And are you able to add a </bagofgold bag take * 10> command?

Also, if you could add ability to take and give percentages that would be amazing

**Comment by Rocologo** [comment]
In next release you will be able to to use give and take and enter * for all online players.

Give/Take percentage still not possible.

**Comment by Rocologo** [comment]
What is the used case for this request? (If you still want that?)
