### ISSUE TITLE
[Meta] Metrics Opt-Out

### ISSUE THREAD

**Issue by Dooder07** [Rocologo/BagOfGold#116]
Punishing those who wish to opt-out of something, well, totally optional (for most plugins, even my own), doesn't help anyone. Personally, I just block bstats.org at the DNS level because of this kind of thing. It's a futile attempt to forcibly collect metrics -- anonymous or not is not up for debate, so this should be seen as an issue to corrected, in my opinion.

**Comment by Rocologo** [comment]
This is what I want to have in return for spending time on my two plugins... I don't want money I want the metrics.

And I have never heard one good reason for not giving me this....

**Comment by Dooder07** [comment]
That's fair enough. But I still believe delaying the startup is a bizarre way to say metrics are important to you. You have to admit that's atypical. The message alone is usually enough.

**Comment by Dooder07** [comment]
That's fair enough. But I still believe delaying the startup is a bizarre way to say metrics are important to you. You have to admit that's atypical. The message alone is usually enough. 

I won't argue with you since you do actually use your data. This plugin is so great I might just go whitelist bstats.org right now. lol

Bastion doesn't fully understand data handling or compliance law and you probably didn't know that. That alone is a good enough reason for me.

**Comment by Dooder07** [comment]
That's fair enough. But I still believe delaying the startup is a bizarre way to say metrics are important to you. You have to admit that's atypical (I don't use a great variety of plugins myself, but I've never seen this before.) The message alone is usually enough to get your point across, it if matters enough to you.

Bastion doesn't fully understand data handling or compliance law and you probably didn't know that. And I don't know Bastion or anything about bstats or it's mission. The Spigot page states our data is being sent to bstats, but it also says to mcstats.org. Checking MetricsManager confirms which but it was pretty ambiguous prior to that. Those facts alone are a good enough reason for me. 

I won't argue with you since you do actually use your data. This plugin is so great I might just go whitelist bstats.org right now. lol
