### ISSUE TITLE
Cant pick up bags

### ISSUE THREAD

**Issue by Lumiexe** [Rocologo/BagOfGold#118]
I can't pick up the money bag, it just stays dropped until despawning. If I use /bog money give <name> 1 , it does not give me a message, and if I check balance after, it tells me "You have   Coin" and bank shows "You have   Coin in the bank"
![6d7fb38e7488b213627b4a01b2a13c34](https://user-images.githubusercontent.com/89649984/146619876-c1f0e98f-6d1f-43c4-8521-7f25c84340ac.png)

I have changed the name of the bag to "Coin" and "Coins"
I have changed skull to custom type.

**Comment by Rocologo** [comment]
What do you mean with this "I have changed skull to custom type."?

Show me the line from the config you changed?

**Comment by Rocologo** [comment]
Is it this you have changed to Custom?

```
  # ########################################################################
  # Reward Type Settings
  # ########################################################################
  itemtype:

    # Here you can set the type of item to be dropped.
    # You can choose between "ITEM","KILLED","SKULL","KILLER", "GRINGOTTS_STYLE". The default is SKULL.
    # The value will be showed above the item.
    # ITEM: The reward is dropped as a normal Minecraft item.
    # KILLED: The reward is dropped as the head of the mob/player you killed.
    # SKULL: The reward is dropped as a SKULL with a custom texture. You can generate custom texture value
    # and custom texture signature at http://mineskin.org
    # KILLER: The reward is dropped as the killers head.
    # GRINGOTTS_STYLE: The reward is dropped as Gringotts Items.
    # 
    # OBS: If the Gringotts plugin is installed and support not disabled, the droped item will be the Gringotts chosen item.
    reward_itemtype: SKULL

```

**Comment by Lumiexe** [comment]
This is what I have it set to, currently:

>  # ########################################################################
  # Reward Type Settings
  # ########################################################################
  itemtype:

    # Here you can set the type of item to be dropped.
    # You can choose between "ITEM","KILLED","SKULL","KILLER", "GRINGOTTS_STYLE". The default is SKULL.
    # The value will be showed above the item.
    # ITEM: The reward is dropped as a normal Minecraft item.
    # KILLED: The reward is dropped as the head of the mob/player you killed.
    # SKULL: The reward is dropped as a SKULL with a custom texture. You can generate custom texture value
    # and custom texture signature at http://mineskin.org
    # KILLER: The reward is dropped as the killers head.
    # GRINGOTTS_STYLE: The reward is dropped as Gringotts Items.
    # 
    # OBS: If the Gringotts plugin is installed and support not disabled, the droped item will be the Gringotts chosen item.
    reward_itemtype: SKULL

**Comment by Rocologo** [comment]
That is fine, What do you mean with this "I have changed skull to custom type."?

**Comment by Lumiexe** [comment]
I think I mistyped, I meant that "I have changed itemtype to skull"

But still just shows as blank amount of coins

**Comment by Rocologo** [comment]
Ok, I had to be sure that you did not change something special.

Try to do this

1) Enable debug mode "/mh debug"
2) Drop a bag /bag money drop 10"
3) Walk into the dropped bag (only one time)
4) Show me the output in the server log from 1) to 3)

**Comment by Rocologo** [comment]
Closed because I didnt get an answer
