### ISSUE TITLE
init crash

### ISSUE THREAD

**Issue by hitanol** [Rocologo/BagOfGold#119]
Paper version git-Paper-267 (MC: 1.18.2) 
Vault 1.7.3-b131
ProtocolLib 4.8.0
EssentialsX 2.19.4

enabled with plugman, in server reboot plugin was automatically disabled
https://pastebin.com/qTujRF1R

**Comment by Rocologo** [comment]
Please explain what you did very detailed

1) was this your first time Install or an upgrade? 
2) is it the new plugmanx you use or the old version?

**Comment by hitanol** [comment]
first time install, i tried unloading the plugin and deleting the plguin folder and loading it but its the log in the pastebin link...

plugmanx

**Comment by Rocologo** [comment]
Okay I have actually newer tried that. I have tested disabling and enabling using plugman in the past, but that is maybe 2 years a ago.

**Comment by hitanol** [comment]
in my case it crashed at startup and enabling with plugmanx

**Comment by Rocologo** [comment]
I will try make some fresh installs to night when I'm off work

**Comment by Rocologo** [comment]
I checked the log again and now I see what's the problem. You have disabled data collection to bstats.org.

**Comment by Rocologo** [comment]
So if you enable bstats it will startup
