### ISSUE TITLE
Duping and nametag bug?

### ISSUE THREAD

**Issue by The0utlaw** [Rocologo/BagOfGold#12]
When dropping the item, it seems to re-appear in your inventory and be on the floor, causing money duping on my server.
And nametags do not show up at all.

**Comment by The0utlaw** [comment]
https://prnt.sc/i1yyju

**Comment by Rocologo** [comment]
What MobHunting version do you use?
What MC version? 
Do you use the BagOfGold plugin?

**Comment by Rocologo** [comment]
Are you in creative or survival?

**Comment by Rocologo** [comment]
Okay... you do ofcause use BagOfGold :-)

Please check that you run newest versions of BOTH BagOfGold and MobHunting

Use

/.mh ver
/bag ver

**Comment by The0utlaw** [comment]
I updated both plugins yesterday and keep them up to date as much as possible.
MobHunting 5.4.2
BagOfGold 1.0.4

In Creative, the bag is droppable and the item does not re-appear in inventory, although in survival it will re-appear in the players inventory along with dropping on the floor, causing it to be picked up and therefore duplicating in-game money.

As for the name-tags of the bags of gold i do not know what could be causing this.

**Comment by The0utlaw** [comment]
I have not tested the plugin(s) with a playerbase yet as i am still setting up the server this was just a bug i found i thought you needed to kow about.
And my apologies to writing a review on the spigot page, right after i wrote the review i found the GitHub issues page.

**Comment by Rocologo** [comment]
The bag is not dublicated on niether my test-server nor my prod-server. So something is different in your setup, and we need to find out what this is. I can't find and fix the bug if I can't see it. 

You dit not tell me what

/version 

writes? I need the full string/text.

**Comment by The0utlaw** [comment]
This server is running 'BagOfGold 1.0.4'.MobHunting 5.4.2

**Comment by Rocologo** [comment]
Well, this is not what I asked for...

Run "/version" in the console and get me the output.

**Comment by The0utlaw** [comment]
i did i forgot to add it to the comment, i added a printscreen link in

**Comment by The0utlaw** [comment]
https://prnt.sc/i2b6oe

**Comment by The0utlaw** [comment]
ok.. so i just threw the bag of gold and now for whatever reason the plugin is working perfectly?
https://prnt.sc/i2b7zp even the name tags work now

**Comment by Rocologo** [comment]
Your server is 113 versions behind. Upgrade your server. Why dont you upgrade to MC 1.12.2?
