### ISSUE TITLE
Hello 

### ISSUE THREAD

**Issue by Hel111** [Rocologo/BagOfGold#121]
what is the command to deposit money in the npc bank?
And how create The physical bank?

**Comment by Rocologo** [comment]
Please check documentation before asking

/bagofgold bank balance (admin)
/bagofgold bank take (admin)
/bagofgold bank give (admin)

Sendt fra Samsung Galaxy S10+



-------- Oprindelig besked --------
Fra: Hel111 ***@***.***>
Dato: 21.07.2022 11.46 (GMT+03:00)
Til: Rocologo/BagOfGold ***@***.***>
Cc: Subscribed ***@***.***>
Emne: [Rocologo/BagOfGold] Hello (Issue #121)


what is the command to deposit money in the npc bank?
And how create The physical bank?

**Comment by Hel111** [comment]
but is it only for admins? or can also users?

and you did not answer me about how to do the physical shop

**Comment by Rocologo** [comment]
It's only for admins.

The idea is that the rules must be like in the real world. If you have some gold you want to store in a Bank you will have to walk to bank and get it stored. You can't do a wireless transfer of physical money 💰



Sendt fra Samsung Galaxy S10+



-------- Oprindelig besked --------
Fra: Hel111 ***@***.***>
Dato: 21.07.2022 14.33 (GMT+03:00)
Til: Rocologo/BagOfGold ***@***.***>
Cc: Rocologo ***@***.***>, Comment ***@***.***>
Emne: Re: [Rocologo/BagOfGold] Hello (Issue #121)


but is it only for admins? or can also users?

and you did not answer me about how to do the physical shop

**Comment by Rocologo** [comment]
The physical shop can only be signs or an NPC



Sendt fra Samsung Galaxy S10+



-------- Oprindelig besked --------
Fra: Hel111 ***@***.***>
Dato: 21.07.2022 14.33 (GMT+03:00)
Til: Rocologo/BagOfGold ***@***.***>
Cc: Rocologo ***@***.***>, Comment ***@***.***>
Emne: Re: [Rocologo/BagOfGold] Hello (Issue #121)


but is it only for admins? or can also users?

and you did not answer me about how to do the physical shop

**Comment by Hel111** [comment]
Ok, thanks. 

keep up these cool things you do :)
