### ISSUE TITLE
Feature request: per world drop rules

### ISSUE THREAD

**Issue by Roos-Skywalker** [Rocologo/BagOfGold#122]
Please allow server owners to config whether the money can be dropped on the ground for other players to pick up or to config whether players can pick up the money in a given world. This is to help with dupe prevention, if a dupe is found server admins can temporarily disable this form of trading while waiting for a fix.

On the topic of dropping: it would also be cool if there was a per world toggle for the money bag to be kept in inventory on death.

**Comment by Rocologo** [comment]
Please elaborate that. 

You would like at to be able to disable the player can pickup/drop money on ground? 

1)I would prefer to spend time on finding a dupe bug, if you have found one and you can reproduce it? 

2)I think it would give a lot of problems if the player could not drop/pickup the bags. Economy wise! 



Have you found a dupe bugs?

**Comment by Roos-Skywalker** [comment]
You would like at to be able to disable the player can pickup/drop money on ground?
Yes.

Have you found a dupe bugs?
No, not yet.

For my usecase specifically, I split my currency across different worlds. Player trading is extremely tricky because of that. Not everyone has the resources to run a Bungee server network. It would be helpful to have more control over the gold bag because what I am doing is unsupported by almost every shop plugin in existence, thus I will need to workaround future possible issues. Trust me I have asked for devs to support this feature but it is not worth their time to implement.

**Comment by Rocologo** [comment]
I have about 6 or 7 worlds on my server without using Bungee. Thats not a problem IF you use WorldGroups and keep your worlds either purely Survival OR Creative. Normal playser should not be allowed to change gamemode only staff, because they will be able to cheat. This is the nature of Creative. You can fly and have all the resources you need, this also go for money items.

**Comment by Rocologo** [comment]
It does not make sense to disable an economy plugin and it would make development too complex.
