### ISSUE TITLE
Compatibility with "Minepacks" plugin

### ISSUE THREAD

**Issue by Q2Lummox** [Rocologo/BagOfGold#123]
Basically the problem is that when you put money in the backpack, it is not recognized.

Would it be possible to check if there is money in the backpack, and recognize it as if you carry it in the normal inventory?

**Comment by Rocologo** [comment]
It seems that Minebacks is not complient with PerWorldInventory, MyWorlds and Multiverse Inventories. This means that Minepacks can be used to move items from one gamemode to another or from one world to another. This would ruin your economy on your server. 

For this reason you would actually have to ask me to deny players to move there money into there backpack. 

You should ask the Developer of Minepacks to support different Inventories in different Worlds/Worldsgroups like f.ex. MyPets do it. This way you can dedicate diffrent worlds to either Creative or Survival.
