### ISSUE TITLE
Players unable to pick up bags

### ISSUE THREAD

**Issue by SykoUSS** [Rocologo/BagOfGold#126]
Running 1.19.2 with 

Plugins (50): AdminAnything, AdvancedEnchantments, AdvancedPets, AntiPopup, BagOfGold, BeautyQuests, BeautyQuestsAddon, Citizens, CommandPanels, DiscordSRV, dtlTraders, Duels, DungeonParties, dynmap, Essentials, EssentialsChat, EssentialsSpawn, FastAsyncWorldEdit (WorldEdit), FleshLeather, floodgate, Geyser-Spigot, GriefPrevention, HolographicDisplays, LevelledMobs, LibsDisguises, LuckPerms, mcMMO, MCPets, MiniMOTD, MobHunting, ModelEngine_Beta, Multiverse-Core, Multiverse-Inventories, Multiverse-Portals, MythicDungeons, MythicMobs, PlaceholderAPI, PlayerAuctions, ProtocolLib, pvparena, QuickShop, Sentinel, ServerSigns, SpawnerMeta, TAB, TigerReports, UltimateTimber, Vault, WorldGuard, WorldGuardExtraFlags

Plugin was working fine, then after a restart no players were able to pick up bags. 
No errors in console, no errors in debug

**Comment by Rocologo** [comment]
That sounds really strange.

Enable debug with /mh debug and /bag debug and show me the full log from a server restart



Sendt fra Samsung Galaxy S10+



-------- Oprindelig besked --------
Fra: SyKo ***@***.***>
Dato: 05.09.2022 01.55 (GMT+01:00)
Til: Rocologo/BagOfGold ***@***.***>
Cc: Subscribed ***@***.***>
Emne: [Rocologo/BagOfGold] Players unable to pick up bags (Issue #126)


Running 1.19.2 with

Plugins (50): AdminAnything, AdvancedEnchantments, AdvancedPets, AntiPopup, BagOfGold, BeautyQuests, BeautyQuestsAddon, Citizens, CommandPanels, DiscordSRV, dtlTraders, Duels, DungeonParties, dynmap, Essentials, EssentialsChat, EssentialsSpawn, FastAsyncWorldEdit (WorldEdit), FleshLeather, floodgate, Geyser-Spigot, GriefPrevention, HolographicDisplays, LevelledMobs, LibsDisguises, LuckPerms, mcMMO, MCPets, MiniMOTD, MobHunting, ModelEngine_Beta, Multiverse-Core, Multiverse-Inventories, Multiverse-Portals, MythicDungeons, MythicMobs, PlaceholderAPI, PlayerAuctions, ProtocolLib, pvparena, QuickShop, Sentinel, ServerSigns, SpawnerMeta, TAB, TigerReports, UltimateTimber, Vault, WorldGuard, WorldGuardExtraFlags

Plugin was working fine, then after a restart no players were able to pick up bags.
No errors in console, no errors in debug

**Comment by SykoUSS** [comment]
here is the latest log, I can't see any errors 
[https://drive.google.com/file/d/1kuEg0FgJvmjqFtlJp0p0BQNuNxsCWNHH/view?usp=sharing](url)

**Comment by SykoUSS** [comment]
It looks to be an issue with the config. If I change the reward rounding to anything it breaks even if I set it back to default until I delete the config stop the server and let it regenerate

**Comment by Rocologo** [comment]
Okay thats strange, but now I have something to test, when I get back from work to see if I can reproduce the bug. 

Where exactly is you changing the reward_rounding ? Is it in corebagofgold.yml, bagofgold.yml og mobhunting.yml ?

**Comment by SykoUSS** [comment]
bagofgold(bog) config.yml, or bagofgoldcore.yml. The 'bog' config.yml seems to actually change things, but both had to be regenerated to fix the issue. I'm trying to set a decimal value of #.## according to the comments in file I would use '0.01' but that causes the pickup issue if I change it in one the other or both

**Comment by Rocologo** [comment]
My intention is actually the Corebagofgold.yml should be the one in control and the two others is only needed if you are upgrading from an VERY old version. If reward_rounding in BagOfGold.yml or MobHunting.yml is used this is a bug.

I think I will remove all the redundant fiends in BagofGold.yml and MobHunting.yml so it will become easier for the server owners to know where to change the values and easier for me when maintaining the code. (After I have made this change :-) ).

**Comment by Rocologo** [comment]
I have worked alot on the Bag pickup/drop/moving. I cant tel if it is fixed, but I will need  a new report and a way to reproduce the bug, before I can fix it.
