### ISSUE TITLE
Money Bags and Mobs

### ISSUE THREAD

**Issue by Darklom** [Rocologo/BagOfGold#128]
Players have reported having issues with them dying and a mob picking up their money bag which nulls the amount (The player loses the money when they pick it back up) and it simply turns into a playerhead.

BagOfGold 4.2.0

Paper version git-Paper-135 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) (Git: eff22eb)

**Comment by Rocologo** [comment]
Please provide a way to reproduce the problem. Im not able to get in a situation like the above and I can therefor not fix a problem I cant see...
