### ISSUE TITLE
Bag of gold reverts to item when broken by water immediately after placing

### ISSUE THREAD

**Issue by SykoUSS** [Rocologo/BagOfGold#130]
Pretty much as stated in the title

If a head type BOG item is broken by flowing water a desync happens causing the had to revert to a normal item, a player can replace the head item in the prior location and break it manually or even by flowing water again to return it to a BOG item

**Comment by Rocologo** [comment]
Fixed in v4.5.0 notice that you will need my new library

https://www.spigotmc.org/resources/customitemslib.106375/
