### ISSUE TITLE
BagOfGold Creative Mode Dupe Glitch

### ISSUE THREAD

**Issue by rackgaming** [Rocologo/BagOfGold#137]
New issue: when in creative mode, it dupes the bagof gold from your inventory if you give yourself too much gold causing gold to drop everywhere while flying
New issue today: When giving a bagofgold from console, it does not combine and when you combine it disappears until you move another item around in your inventory

Steps to reproduce: Give yourself a bag of gold > go to console give yourself a bag of gold > combine it with that other bag of gold > gold disappears.

**Comment by Rocologo** [comment]
Bug confirmed and fixed in next release.

**Comment by rackgaming** [comment]
There seems to be another dupe bug with the customitemlibs though, people can place a mob head on the ground break it and it gives them another one.
