### ISSUE TITLE
Plugin thinking player is offline

### ISSUE THREAD

**Issue by CampingSteve** [Rocologo/BagOfGold#14]
when a player joins and gets some money....it doesn't add to their balance because it thinks they are offline when they are not.

**Comment by CampingSteve** [comment]
/eco give player amount gives the player money but because mobhunting thinks they are offline it gives a bag of the correct value but their Balance is 0.  I tried giving the player money by /mh give <player> <amount> and it said they are offline even though they weren't.

**Comment by Rocologo** [comment]
This sounds very strange i use standard minecraft when i test if the player is offline. Did you spell the name correct?

**Comment by CampingSteve** [comment]
Yes I did...it was on first join...when they relogged...the balance was added...strange.

**Comment by Rocologo** [comment]
Ahh on first MobHunting tries to get their balance from Essentials.

**Comment by Rocologo** [comment]
How does v1.0.5 work for you?

**Comment by CampingSteve** [comment]
So far great 😁

**Comment by CampingSteve** [comment]
Added the release to my server and no problems found yet😁

**Comment by Rocologo** [comment]
Im happy to hear this :-)
