### ISSUE TITLE
How could I make CMI`s money to be BagOfGold?

### ISSUE THREAD

**Issue by MuYuehe** [Rocologo/BagOfGold#145]
sorry, I cant found a way to do this.

**Comment by Rocologo** [comment]
I dont know CMI that well. But since CMI uses Vault and CMI is not an economy plugin, it should work out of the box. 

Install both plugins. Enable debug mode using "/Bag debug" and check the debug information in the server console, when you start your server.

**Comment by Rocologo** [comment]
So you should NOT use the recompiled VAULT and NOT use the injector.

**Comment by MuYuehe** [comment]
ok, I will try later.
by the way, I found that CustomItemsLib integrates CMI. I don't know what it does

**Comment by MuYuehe** [comment]
There is no output on the console. That [04:43] is used to display the time when the drop disappears. It should not be caused by it

**Comment by Rocologo** [comment]
If there is no output something must be wrong with the start up. Please check the debug information. Or try to show me your serverlog using pastebin.com

**Comment by MuYuehe** [comment]
https://pastebin.com/6McfAtGB

**Comment by Rocologo** [comment]
These lines are not normal




  1.
[21:41:29] [Server thread/INFO]: [BagOfGold][Debug] onInventoryCloseEvent: Adjusting Player Balance to Amount of BagOfGold in Inventory: PlayerBalance: {player: Name:valuuntu, WorldGrp:default, GameMode:SURVIVAL, Balance: 0.0(+0.0), BankBalance: 0.0(+0.0)}
  2.
[21:41:29] [Server thread/INFO]: [BagOfGold][Debug] there was no difference


This means that another plugin is calling the InventoryCloseEvent all the time.

You will need to find this plugin.


But it also means that Bagofgold is loaded and you should be able to pick up bags

Try to drop a fresh new bag and see if you can pick it up. Check the console for messages

/bag money drop 10

Sendt fra Samsung Galaxy S10+



-------- Oprindelig besked --------
Fra: MuYuehe ***@***.***>
Dato: 14.08.2023 15.46 (GMT+01:00)
Til: Rocologo/BagOfGold ***@***.***>
Cc: Rocologo ***@***.***>, Comment ***@***.***>
Emne: Re: [Rocologo/BagOfGold] How could I make CMI`s money to be BagOfGold? (Issue #145)


https://pastebin.com/6McfAtGB

**Comment by MuYuehe** [comment]
![image](https://github.com/Rocologo/BagOfGold/assets/93329319/e3cca83f-910c-4a8a-a511-ccef1c1ca28e)

**Comment by MuYuehe** [comment]
Sorry, it was too late for me yesterday. This is a test I did today with a completely new server. As you can see on the picture, there are only these few plugins. However `onInventoryCloseEvent` is still fired because I open the backpack Then turn it off. So I don't think it has something to do with other plugins.
![image](https://github.com/Rocologo/BagOfGold/assets/93329319/825c1dec-b2c3-4f0f-a4a2-fdafe0c0fc53)

**Comment by MuYuehe** [comment]
Looks like using essentialsX is the best way.
Maybe I can ditch CMI, after all my server is still in development for now.

**Comment by Rocologo** [comment]
I still dont understand why you cant pick up the bags. Thats VERY strange. Are you building SpigotMC using Buildtools? or how do you get your server jar file?

**Comment by Rocologo** [comment]
I have made a "clean" server install many time to check if everything works.

**Comment by Rocologo** [comment]
One thing you could test is to remove ProtocolLib.jar and then start your server. If you the give yourself a bag  using "/bag money give playername 100" and point at the bag in the inventory, this should show you some "hidden" lores, which is used to identify the bag. Take a screenshot of the Lores so I can see if the look as expected.

**Comment by MuYuehe** [comment]
Ok, I will try a new server start again, my server packages and plugins are downloaded from the official website. I only use three packages: BagOfGold, Vault and CustomItemsLib, and I will not modify any other values.
I will record a video and send you the server console output.

**Comment by MuYuehe** [comment]
[https://pastebin.com/uiuJh16K](url)
[http://alist.muyuehe.top/](url)
![image](https://github.com/Rocologo/BagOfGold/assets/93329319/ab31acb4-4d79-4d56-8bd1-cf8b7a3a972d)

**Comment by Rocologo** [comment]
Ohhh I just saw the message about that you have no Permission and the I realized that you dont have a Permission plugin. 

You will need to add a Permission plugin. I use PermissionEx : https://www.spigotmc.org/resources/permissionsex.108323/ 

But you can use anyone which is compliant with Vault. My guess is that this is your core problem. I have NEVER tested my plugins without a Permission plugin :-)

**Comment by Rocologo** [comment]
And you will need to setup Permissions for all your plugins.

**Comment by MuYuehe** [comment]
I started the server again and set myself as OP.
OP has all permissions, but still can't pick it up.

**Comment by Rocologo** [comment]
Like I said I have never tested my plugins without a Permission plugin :-) 

You will need a permission plugin anyway before you let other people into your server. It would be crazy to do thatr without a Permission plugin.

**Comment by Rocologo** [comment]
And by the the way:  OP only have the permissions that the plugin-developer gives the OP player. You cant be sure this system works its not meant to be used on servers with public access

**Comment by Rocologo** [comment]
I will of cause see if this can be fixed, but it will take some time to do the development and testing.

**Comment by MuYuehe** [comment]
Yes, I agree with you. Actually, I have switched CMI to EssentialsX on my production server, and it works fine with BagOfGold now. For me, I have OCD in some aspects, When I find a good plug-in, I will start to build around it. The BagOfGold plug-in is very clever in terms of economic construction. I like your approach very much. Although CMI also wants to give good plug-ins, but I still discarded it.
Overall, thank you very much for this plugin and for your patient reply. But allow me to ask one last question:
I don't know how compatible BagOfGold is with Shopkeepers, but I see testing is in progress and I'm using Shopkeepers at the same time.
Here is the error I get when I use it:   [https://pastebin.com/3AfVpFEC](url)
It happened when I put the bag of gold in the price column of shopkeepers.
I don't know if this error belongs to BagOfGold

**Comment by Rocologo** [comment]
1) You should be able to use CMI together with BagOfGold. I have tested this many times. At least with CMI Holograms and messages. 
2) BagOfGold should work with Shopkeepers, but this is one of the newer featues and it seems that you have found a bug. :-(  Are you able to explain (in details) what I should to do reproduce this error? If you can explain this I can fix the bug. It looks like you are clicking on an empty slot or something?  How does the inventory (The shop) look like?

**Comment by MuYuehe** [comment]
This error occurs when I open the shopkeepers gui, click on the bag of gold and put it in the slot

**Comment by Rocologo** [comment]
Do you open the Shopkeeper GUI to edit the content or as a player how wants to buy/sell/trade?

**Comment by MuYuehe** [comment]
Oh, sorry, I forgot that there are two guis, it happened when I opened the edit Gui

**Comment by Rocologo** [comment]
Yes, thats why I asked for details :-D

**Comment by Rocologo** [comment]
> CMI doesn't work well with EssentialsX

Okay. It have of cause not tested all combinations. This is an extremely big job.

**Comment by MuYuehe** [comment]
> > CMI doesn't work well with EssentialsX
> 
> Okay. It have of cause not tested all combinations. This is an extremely big job.

Yes, plugins that provide core functions like these are difficult to use together, and it is a very large workload for those who maintain them to be compatible

**Comment by Rocologo** [comment]
Exactly. Most of the new bugs which is found are because another developer has changed something in his plugin, which affects mine.
