### ISSUE TITLE
Deposit keeps object in inventory but without "value"

### ISSUE THREAD

**Issue by P0Pss** [Rocologo/BagOfGold#17]
If I deposit $100 then it says that it's gone into the bank and that I have 0 balance, but the bag of gold is still in my inventory with $100 if I withdraw it then the bag of gold will say its got $200, when the npc still says $100. Basically the object stays in the inventory without any monetary value

**Comment by Rocologo** [comment]
Which server version do you use?
Which MobHunting version?
Which BagOfGold version?

**Comment by P0Pss** [comment]
Server version is 1.12.2
Mobhunting is 5.4.6
BagOfGold is 1.0.6

Forgot to mention that its using an npc for the banking if it helps

**Comment by Rocologo** [comment]
So its only when you use the npc?

Yes it helps, when i do the testing

**Comment by P0Pss** [comment]
Sorry, I'm an idiot, I was in creative.....
Apologies

**Comment by Rocologo** [comment]
Ha ha, no worries :-)
