### ISSUE TITLE
Duping of money bags

### ISSUE THREAD

**Issue by Mayzone** [Rocologo/BagOfGold#18]
The player doing this is in survival and has almost no permissions.

I open a normal double chest and i hold shift pressing bag of gold in my inventory slot 1-9. This creates another bag in inventory slot while the one i put in chest is still there, i then keep doing this 5times or so and stack the money in the chest and when done, ill drag the money bag that is in the chest and hold it over outside the chest gui and press esc and now that stacked money is dropped outside the chest. 

Usually in the beginning of trying this the money will disappear either in inventory or chest, or just totally delete all the money but if i keep trying, it suddenly stays in chest.

mobhunter version: 5.4.6
bagofgold: 1.0.6
spigot version 1.12.2

**Comment by Rocologo** [comment]
I cant replicate this problem. When I do shift click on a bag, it is removed immidiately. No dublication. The same goes when I press ESC the item is dropped on the gound and removed from the inventory.

Is you Spigot server updated?

How many versions are you behind. Try /versions in the console.

**Comment by smithy9901** [comment]
Same problem, spigot latest version.

**Comment by Rocologo** [comment]
I does not happen on my server, so we need to find out what trigger this? I cant solve a this problem without your help. 

Maybe is a conflict with another plugin???

**Comment by Rocologo** [comment]
I have tried to change the BagOfGold Event priority in build 582,

http://jenkins.lindegaard.one:8180/job/MobHunting/582/

please test if this makes a difference?

**Comment by Rocologo** [comment]
Instantout found a way to reprodure and I found a way to fix it. I hope this is the same duplication bug you found. Please test v1.1.0

**Comment by Rocologo** [comment]
And MobHunting 5.6.1

They will both be released within 30 min.

**Comment by Rocologo** [comment]
released

**Comment by Mayzone** [comment]
Nice nice
