### ISSUE TITLE
Player head update.

### ISSUE THREAD

**Issue by SirMittens** [Rocologo/BagOfGold#22]
Hello! I recently stumbled upon your plugin. very well done by the way, but there seems to be an issue when a player buys/sells an item. the bag of gold updates to a player head. I am aware that it is a player head item. but is there any way of stopping it from turning to one on purchase/sell

Thanks in advance

**Comment by Rocologo** [comment]
Hi 

You have to be more specific on what you are doing :-) I must be able to replicate this bug to fix it.

Buy/Sell which item??? Using which plugin? I have done a lot of testing on this but I cant replicate the problem?

**Comment by SirMittens** [comment]
hey, just any item does it. we are using dtl traders for shops

**Comment by Rocologo** [comment]
Please explain in details what you are doing. I cant guess....

**Comment by SirMittens** [comment]
right, I simply used the Mob hunting command to give myself 3000 currency within a gold bag. made a dtl traders shop selling multiple random things (saplings, gold blocks, diamond blocks, emerald blocks). soon as I buy/sell an item and the bag of gold value updates it turns back to a player head.
I also tested this with the auction plugin. same thing

**Comment by Rocologo** [comment]
Thank you, now i think i understand how to do the testing...

**Comment by Rocologo** [comment]
Could I ask you to test this with BagOfGold V1.1.3 ?

**Comment by SirMittens** [comment]
Hey sure will do, sorry for the delay was out of town

**Comment by Rocologo** [comment]
I have moved to MC 1.13 I hope you will move as well :-)
