### ISSUE TITLE
Bag itemMeta is displayed

### ISSUE THREAD

**Issue by Zoiter7** [Rocologo/BagOfGold#28]
Spigot version: 1.8.8
BagOfGold version: v1.17

Hello, when you divide the bag item in your inventory the item meta is displayed.
If you don't divide there isn't any problem.

http://oi63.tinypic.com/mx20at.jpg

Regards

**Comment by Zoiter7** [comment]
Yes, I have the last version available of ProtocoLib for my version, and it's only occurred that I mentioned after, when you split the item, the bag, but if you don't split it works fine.

And I tested to change the world with the item bag and the money doesn't loss.

Someday, of course ,the old versions will dropped like 1.8 but it seems not yet, maybe in a few months

**Comment by Rocologo** [comment]
FYI - I have added PlaceHolders for Balance and Bank_Balance, but this is only for MC1.13 / >BagOfGold V2.0.2

**Comment by Zoiter7** [comment]
Thanks for the placeholder, could you update the github repo please?

**Comment by Rocologo** [comment]
The v2.0.3 is pushed to the repo today
