### ISSUE TITLE
500 gold on spawn. Put gold in chest, disconnect/reconnect, get 500 more gold. Forever!

### ISSUE THREAD

**Issue by Xorgone** [Rocologo/BagOfGold#3]
This plugin is GREAT! I love it so far. only bug I've seen however is a gamebreaker, and I can't figure out what is causing it.

When you spawn in, it starts you with 500 gold. That is all fine and dandy, except if you put your gold into a chest, and then disconnect/reconnect, it will spawn you in with 500 more gold ad infinitum. 

I'm sure this is an easy fix, but I couldn't find it in the settings anywhere.

Thanks for your time, and thanks for your work on the plugin!

**Comment by Rocologo** [comment]
Thank you for creating a ticket. I will find a fix as soon as possible. Unfortunately I am not able to look at the problem until I get back from work. Tonight. CET+2.

**Comment by Xorgone** [comment]
No problem bud :)

**Comment by Rocologo** [comment]
Just an update, i worked on the issue last night, more than two hours. I was able to reproduce the bug, but when i started to debug and make changes, i realized that i had to do major changes in the code to handle inventory movements correct.

**Comment by Rocologo** [comment]
So i was not able to finish the changes and do rhe needed testing yesterday. 

I dont know how much time i have to do development the next days, because of xmas, but i hope i can fix this problem fast. It IS a MAJOR problem

**Comment by Rocologo** [comment]
I hope i fixed this problem in newest snapshot on my Jenkins server

https://fractal.lindegaard.one:8181/job/MobHunting/ (Build 517+)
https://fractal.lindegaard.one:8181/job/BagOfGold/ (Build 29+)

Please confirm

**Comment by Rocologo** [comment]
I have tested a lot now, and made big changes in the way Inventories i handled...  

Please test V0.9.3 and MobHunting V5.2.3 .... you need to upgrade both plugins, to get it fixed.

**Comment by Xorgone** [comment]
I am testing it right now, and I can say that the bug I experienced before cannot be reproduced! It seems to be working correctly now. I will poke around with it a little more, but it looks great right now. :) 
Thanks again! Your plugin is amazing.

Do you know if it would be possible to have nuggets, ingots, and blocks be the currency? There was once a plugin called GoldIsMoney and the money was built around Nuggets, ingots, and blocks, and the whole system being based on 9. (9 nuggets to an ingot. 9 ingots to a block.) It worked really well.
Thanks for your plugin and your time!

**Comment by Rocologo** [comment]
Personally I like the "BagOfGold" more :-) today BagOfGold support one item (ex. gold_ingot) but I will see if it is possible for me to make it three items. I think I have most of the code I need now.

I cant promise the I have fixed all bugs. I had handle a lot of GUI's. It was not only a chest problem. I also checked all the other gui's. Like Shulker_box, Workbench, Ender_chest, Furnace, all guis where I could place the "bagofgold item".

**Comment by Xorgone** [comment]
I had a problem last night with having gold in my inventory but being unable to buy from a chestshop sign saying that I didn't have enough money. So I had to disable the plugin again but kept mobhunting enabled

**Comment by Rocologo** [comment]
Okay, I did not test the newest version against ChestShop, but I actually have chestshop on my testserver to test with.... i will do some testing and get back to you :-)

**Comment by Rocologo** [comment]
I have tried chestshop and I cant replicate the problem?

**Comment by Rocologo** [comment]
I have also tested Bossshop - no problems either....

**Comment by Xorgone** [comment]
Ill take another look tonight, but I had a player complain it wasn't working. I then took his gold andtested, and it didn't work for me either. I will look again tonight but idk

**Comment by Rocologo** [comment]
I have found another bug when moving between inventories. I will soon release 0.9.6

**Comment by Rocologo** [comment]
Do you still having problems with ChestShop and BagOfGold??

**Comment by Xorgone** [comment]
I haven't had the time to test it out on my live server, but I will give it a go tonight or tomorrow and let you know! I will reply back as soon as I find something good or bad.

Thanks again!
