### ISSUE TITLE
Players have 0 balance after depositing

### ISSUE THREAD

**Issue by braceyourself07** [Rocologo/BagOfGold#31]
Not sure if this is related to a prior bug mentioned in github, but when a player joins for the first time they get a certain amount of gold.  When they use a deposit bank sign, they get a success message saying it worked.  But when they click on balance or withdraw, it says there is no money.

I then did /eco give player 1000 and had them purchase something in a ChestShop, which worked fine. And they deposited the remaining into the bank, but when they checked balance or tried to withdraw it said they don't have any money in the bank. 

We are on our final week of testing before opening the server to our community and we would really like to use this plugin, but this would obviously be game-breaking if we did.  We are using the most recent version available on spigotmc for BagofGold and MobHunting.

Thanks!

**Comment by braceyourself07** [comment]
BagofGold v2.0.4
MobHunting v6.0.3

**Comment by braceyourself07** [comment]
Oops, didn't see the 2.0.5 release. Updated and it seems to work! 👌

**Comment by Rocologo** [comment]
I have not changed anything in balance/deposit/withdraw between 2.0.4 and 2.0.5 so if you found a bug, it will also be there in 2.0.5. I think i will do some more testing

**Comment by braceyourself07** [comment]
Yes this is happening to some players.

**Comment by Rocologo** [comment]
I need to know if you use Mulitiverse and PerWorldInventory so i can test on same setup. Or if you use similar plugins? 

I have a test server so i can delete my data from the database and test as a new player. 

Are you using banksigns or an Npc to check bankbalance?

**Comment by braceyourself07** [comment]
No multiverse or perworldinventory, this is just a simple semi-vanilla survival server.  The issue was primarily with banksigns.  I don't recall if the NPC had any issues, or if it did.  I'll ask the folks who tested.

**Comment by braceyourself07** [comment]
Players are saying the banksigns aren't working but the NPC does work.  Interestingly, now the signs don't work at all... like clicking on them does nothing.  I am going to take down the bank signs and just have the players rely on the NPC and see if that is more successful.

**Comment by Rocologo** [comment]
Im at work, but I hope my family :-) will allow me to "play" a little with development tonight. Testing this has higest priority!

**Comment by Rocologo** [comment]
Both banksigns and the npc should work. It not long ago I tested this, so Im pretty sure that it works on my test-server.

**Comment by braceyourself07** [comment]
Hmm.  For some people it works. And for others it doesn't, even on NPC.

Screenshot:
https://brdv.coffee/storage/uploads/4/Discord_2018-08-27_13-09-37.png

**Comment by braceyourself07** [comment]
Should I use MySQL instead of Sqlite, or would this indicate a different problem?

**Comment by Rocologo** [comment]
I think I found the bug. I deleted my database and did "bag money bal rocologo" from the console, and this throw an error in the console, which was a bug. So I think it works now when a new player login.

please help me testing
https://fractal.lindegaard.one:8181/job/BagOfGold/145/

PS. Its not related to sqlite / mysql. It was related to new players, new players not in the database.

**Comment by Rocologo** [comment]
PS. I still having problems if the player opens his inventory in CREATIVE mode and touches the BagOfGold. (I think it is ProtocolLib which removes the Lores from, and the Lores contains the value of the bag) 

You can test this if you disable ProtocolLib. I dont know it this is a bug in ProtocolLib or if it is Creative mode which is changing the Lores. But changing/removing the Lores will easily destroy the Bags value.

I will look in to this to morrow after work.

**Comment by braceyourself07** [comment]
The people I'm having test are people who have not been on the server before.  So they don't have the ability to go into creative mode.

A new player deposited 800 gold using the both the sign and NPC and it still says 0 bank balance.

I tried to use the new pay command with this particular player, and it said that the player was offline. So that may be the source of the issue.

I'll test without ProtocolLib to see if that changes anything.  Thanks for your hard work looking into this.

**Comment by Rocologo** [comment]
Do you get any errors in the server log?

**Comment by braceyourself07** [comment]
Aren't you supposed to be asleep? :D 

No errors, but here is a start-to-finish debug of a new player logging in and testing the bank by depositing gold, but no balance to withdraw.  

https://hastebin.com/xiqoziseli.md

Interestingly, when this player joined, they were given 2x the normal gold amount (6000 instead of 3000).  This player was brand new to the server (an alt of a friend who is helping me test) and never went into creative mode.

**Comment by Rocologo** [comment]
I was actually laying in my bed in the middle of the night .... checking my phone .... :-(

Let mw know if build 146 has changed anything:
https://fractal.lindegaard.one:8181/job/BagOfGold/146/

**Comment by braceyourself07** [comment]
No change. Had a new player log in, deposit everything, and when he withdrew any amount said he did not have enough funds.  We are planning to open our server this weekend, so I think I am probably just going to use the gold system without economy (where players have to turn gold in to currency) or go without a bank and just let players keep their money in their own protected chests.

**Comment by Rocologo** [comment]
Yes. I understand, im running out of time :-( 

But i will still work on this. Do you have a test server too?

**Comment by braceyourself07** [comment]
Yep I can help test!  If I delete the database, that is the same as a new player, correct? The only difficult part about testing this, is that it only seems to happen for players who have joined the server for the first time. So each time we test I have to find someone to help--which is not a problem as we have a large community and many are willing to help.

**Comment by Rocologo** [comment]
I could reproduce the problem for first time users logging on the the server and I think the problems is fixed now.

Try build https://fractal.lindegaard.one:8181/job/BagOfGold/147/

If you want to test as a firsttime user you must 
1) stop the server
2) delete the database (or the record in the database with the player uuid you want to test on)
3) delete the file minecraftserver/world/playerdata/<uuid>.dat
4) start the server

**Comment by Rocologo** [comment]
PS. Yes it is VERY important to me the make BagOfGold stable. I think this is the best economy plugin compared to all other economy plugins I am aware of. And I like the idea about that the players loose their money if they dont take care. :-)

**Comment by braceyourself07** [comment]
Build 147 worked! Got a brand new player in, did the same steps and deposited several hundred gold and was able to withdraw.  Fantastic!  Will continue testing and keep you appraised on the plugin performance. So far so good!

**Comment by Rocologo** [comment]
removed some debug information and uptimized the code 
https://fractal.lindegaard.one:8181/job/BagOfGold/148/
