### ISSUE TITLE
Feature Request:  /bag money banktop?

### ISSUE THREAD

**Issue by braceyourself07** [Rocologo/BagOfGold#32]
In #26 you were addressing a question about Essentials baltop.  I was curious if you could add a command to total the bank's deposited gold and order a top ranking of players with the most banked gold. 

Something like:  **/bag money banktop**

And this would produce, like Essentials baltop, a total amount of gold stored in the bank collectively, as well as a top 10 list of players who have the most money (and how much) in the bank.  That way it can be kept separate from Essentials /baltop and players could look at both lists for the fun/competition of it.

If you did have an easy method to combine on-hand gold with banked gold for a "total wealth" command, that would be awesome but not necessary especially if it is time consuming to write or takes up a lot of plugin overhead.

No urgency to this, was just an idea since a few of my beta testers were asking about it.

**Comment by Rocologo** [comment]
This one is easy. You will get this.

**Comment by braceyourself07** [comment]
Awesome thanks!

**Comment by Rocologo** [comment]
I have started on this. But I have some questions .-)

Since we need to consider its a multi-world server with world groups it not that easy as i first though :-| 

I think there is two options (or more?)

1) I should find top25 in the players current worldgroup (I think this is best?)
2) I should find top25 across all worldgroups. But the thing is that the worlds can have totally different economies. At totally different levels. 

What do you think?

**Comment by Rocologo** [comment]
And actually we shuld think about the gamemode too. Same problem.

**Comment by braceyourself07** [comment]
How about:   /bag money banktop [world]
And it will check survival vs. creative depending on the gamemode of the player.

When someone types just **/bag money banktop**  it will retrieve the current player's world and gamemode and displays results for those specific criteria. 

May want to have the result qualify which world and gamemode so when they type the command by itself and expected a different result they could read the heading and say "Oh I meant to type that while in creative mode".

**Comment by Rocologo** [comment]
"/bag money top" implemented, first try.

https://fractal.lindegaard.one:8181/job/BagOfGold/151/

**Comment by Rocologo** [comment]
When calculating the wealth use both player balance and bankbalance, but if the player hide money in a chest im not able to count them.

**Comment by braceyourself07** [comment]
That's really awesome. I like how you formatted it as a GUI!

Screenshot:
https://brdv.coffee/storage/uploads/4/ApplicationFrameHost_2018-09-02_21-45-39.png

Also works in both gamemodes.  Thanks so much for implementing this!
