### ISSUE TITLE
placing a bag of money, or a money item into a item frame, then removing it from the frame causes the value to double.

### ISSUE THREAD

**Issue by Eeiean** [Rocologo/BagOfGold#33]

**Comment by Rocologo** [comment]
In creative or survival?

**Comment by Eeiean** [comment]
Survival

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Eeiean** [comment]
Creative simply removes the bag of you hit it

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by braceyourself07** [comment]
I'm not the original poster, but I can confirm on this version that I cannot double the value when retrieving gold that has been placed in an item frame while in survival mode. 👍

**Comment by Rocologo** [comment]
Thank you Mike :-)
