### ISSUE TITLE
[Request] Limit money per bag.

### ISSUE THREAD

**Issue by En0tS** [Rocologo/BagOfGold#36]
Please add ability to set max money per one bag.

**Comment by Rocologo** [comment]
I promise i will make this, but i am extremly busy at the moment so it will take some time. :-(

**Comment by Rocologo** [comment]
You finally got this :-)

Please help me with the testing. Im not sure I remembered to set the limit everywhere.

Please use build 711 or newer
https://fractal.lindegaard.one:8181/job/MobHunting/

And build 156 or newer
https://fractal.lindegaard.one:8181/job/BagOfGold/

Please let me know the result of your testing

**Comment by Rocologo** [comment]
please test with build 712 and 157, I found some bugs, when moving over the bags while the inventory is full.

**Comment by Rocologo** [comment]
please test on latest builds
https://fractal.lindegaard.one:8181/job/BagOfGold/
https://fractal.lindegaard.one:8181/job/MobHunting/
