### ISSUE TITLE
Players can take heads out of GUI

### ISSUE THREAD

**Issue by braceyourself07** [Rocologo/BagOfGold#37]
This is minor... when players run **/bag money top** they can take the playerhead from the GUI display and put it in their inventory.

This isn't harmful, but we have an economy system where players can purchase heads using Arcaniax HeadDatabsae, so it's just a minor way they can circumvent the system.  Is it possible to prevent the GUI from being modified by the player?

**Comment by Rocologo** [comment]
Yes, i think i have forgotten to cancel the event that fires when a player click on the heads to take them out.

**Comment by Rocologo** [comment]
Fixed in build 153

https://fractal.lindegaard.one:8181/job/BagOfGold/

**Comment by braceyourself07** [comment]
Thanks!
