### ISSUE TITLE
Duplication issue in version 2.0.7

### ISSUE THREAD

**Issue by Blizliam** [Rocologo/BagOfGold#38]
If a player splits bag of money in half which has an odd integer (or any non integer) value, and then proceeds to drop one of those halves, when they pick it up they will have 0.5 coin more than they started with. I believe the source of this error is in how the dropped money translates to decimal (Or it may have to do with a rounding function). If I drop 25.25 coin on the ground with 25.25 still in my inventory, when I pick up the 25.25 on the ground, my new sum will be 50.25 (It should be 50.5).

Thanks in advance.

**Comment by Blizliam** [comment]
I appreciate your quick fix and reply. It fixed some, but duping still occurs with several splits from one stack all being dropped, and picked up again. I will make a separate ticket for a feature request. I would like the option to disable decimal currency at all.

Thanks again for your quick reactions.

**Comment by Rocologo** [comment]
You dont need a ticket for that, check rounding in config.

**Comment by Rocologo** [comment]
Please on latest builds, I think the rounding problem has been solved now.

https://fractal.lindegaard.one:8181/job/BagOfGold/
https://fractal.lindegaard.one:8181/job/MobHunting/
