### ISSUE TITLE
[Request] Option for disabling decimal currency (Already implemented)

### ISSUE THREAD

**Issue by Blizliam** [Rocologo/BagOfGold#39]
I would like the option to be added to disable decimal currency. For example, if a player had a stack of 5 bagofmoney, and he were to right-click to split the stack, the stack his cursor would hold would be 3 (previously 2.5) and the stack in his inventory would be 2. I personally like the realism aspect of having integer coins.

From a fellow coder, thank you for timely responses and continually committing to this project.

**Comment by Rocologo** [comment]
Set reward_rounding: 1.0 in config.yml in both mobhunting and bagofgold. :-)

**Comment by Blizliam** [comment]
Perfect, many thanks!
