### ISSUE TITLE
Gold not stacking properly when player inventory is full

### ISSUE THREAD

**Issue by braceyourself07** [Rocologo/BagOfGold#40]
https://pastebin.com/heYkkm1x

Using pastebin instead of hastebin since I've been having issues with it lately.

In this glitch, a player was farming guardians and had about 1k worth of money drops.  He was picking them up and his inventory was full, and suddenly there were bags of gold valued at -9k and -10k 
Then after depositing them, he came back to pick them up, and ended up with over 300k gold.

I'm not sure exactly the steps to reproduce this, because it involved a few things over time.  In the log excerpt there is a lot of math and negative numbers.  I figure it's related to the new bag cap feature where players can only have a bag cap of 10k per item. Somehow the math isn't working out properly.

**Comment by Rocologo** [comment]
Yes, just set the number to 999999999 (the limit is the limit in the database for a double presion number)

**Comment by Rocologo** [comment]
I will do some more testing with the new build i just posted on the other ticket.

**Comment by Rocologo** [comment]
I cant reproduce the problem.  My limit is set to 10000,  

And If I try to pickup 10000 while only having space fore 8875 it leaves 1125 on the ground 
![2018-09-18_20 05 36](https://user-images.githubusercontent.com/1008133/45707207-88313600-bb7e-11e8-8c1a-4321b0bb1f6a.png)

**Comment by braceyourself07** [comment]
I asked the player for more info, which is difficult since English is not his first language (and its my only language), but he broke it down for me this way:

Kill a mob, but don't pick up the drop (e.g. inventory full so it spawns a few blocks away from you)
Teleport away (e.g. go back to /spawn or /home)
Go back (/back) 
Try to pick up the gold, and it doesn't have any money.

Before, this is where he got the 10k issue.  But I have since increased the bag cap to something very high.  So he no longer has the -10k bag, but there is still no money when picking up a mob drop if you teleport away (e.g. to unload inventory) and teleport back and then pick it up.

**Comment by Rocologo** [comment]
Well English is of cause not my first language either :-)  Im Danish. 

I will try to see if I can reproduce the bug as described above.

**Comment by Rocologo** [comment]
It worked as intended when I tried...

**Comment by braceyourself07** [comment]
Well, his English is conversational, but when trying to describe what exactly he did--especially if it's complex, like what exactly he dropped, right-clicked on, left-clicked on, etc... he had a hard time describing it--especially when he would insert a negative like 'no' or 'did vs didn't' since that changed the entire meaning of what he was doing. So it took some deciphering but I think we got it.  I'll keep testing on this end.

**Comment by braceyourself07** [comment]
I think we are good here.  I asked the player to try to reproduce it (since he was able to several times before) and he said he cannot reproduce it.  So either the dropping items fix or eliminating the bag cap seemed to have solved this problem.  I'll close and can always re-open if I have other reports.  Thanks so much!

**Comment by Rocologo** [comment]
You are welcome ... This was the last open issue :-) 

I guess I need to invent new features then :-)
