### ISSUE TITLE
Feature request: allow for money drops of vanilla items (e.g. emeralds)

### ISSUE THREAD

**Issue by meswrex** [Rocologo/BagOfGold#41]
[As discussed at spigotmc](https://www.spigotmc.org/threads/bagofgold.283572/page-10#post-3166231), can either BagOfGold or Mobhunting add a Gringotts-like feature to enable currency dropping of vanilla items? For example using the following settings, non-vanilla emeralds are dropped which still remain as BoG or MH currency and can't be traded with villagers:

drop_money_on_ground: true
drop_money_on_ground_itemtype: ITEM
drop_money_on_ground_item: EMERALD

Can these be reconfigured or additional configuration be added to allow for non-currency emeralds to be dropped (possibly without evening requiring Gringotts for users that only use this feature)?

**Comment by Rocologo** [comment]
Originally I made MobHunting so it would work with Gringotts as an eConomy plugin. Ufortunately it seems that Gringotts is not being updated anymore, so I will see if I can add something similar, so that the reward will be Vanilla items. I think I can do this, I just need some time.

**Comment by meswrex** [comment]
Wonderful - no expectation to hurry given the alternative of waiting for Gringotts is never :)
Thanks again.

**Comment by Rocologo** [comment]
V2.5.1 has a GRINGOTTS_STYLE option. check the config.yml

**Comment by meswrex** [comment]
Wonderful! Will try it out this evening!

**Comment by Rocologo** [comment]
I have not had to much time for testing, so please test everything. First release is probably. Not bugfree

**Comment by meswrex** [comment]
Works a treat! No issues so far. I see what you mean regarding taking care not to break the economy.
One quick question: can the floating values of the drops be turned off? I think I might keep them on since they are a nice touch but would be good to know if they can be turned off.

**Comment by Rocologo** [comment]
Im not sure which flosting values you are talking about?

**Comment by meswrex** [comment]
When I configure both BagofGold and Mobhunting to drop emeralds as items using the new gringotts_style mode, the dropped emeralds have floating text above them just prior to picking them up that notes a value, fractional if there is no rounding.

**Comment by Rocologo** [comment]
Okay understood, i will have to investigate this. It was my plan to make it exactly like gringotts. Without the text above the emerald blocks

**Comment by Rocologo** [comment]
Hi again

I have tested this and fixed a bug, but I dont have the value as an item label???

https://fractal.lindegaard.one:8181/job/BagOfGold/188/

**Comment by Rocologo** [comment]
Fixed in V2.5.2
