### ISSUE TITLE
PaperSpigot/PaperClip+Citizens NPC Banker

### ISSUE THREAD

**Issue by Gronsten** [Rocologo/BagOfGold#43]
Roco,

Just switched from Spigot to Paper.  Only thing that won't work is Banker NPC.  On server load, Citizens states "bagofgoldbanker" trait doesn't exist.  NPC's are still present, but don't do anything.  Trying to create a new banker npc only returns BoG help menu.  Let me know if I can provide more info.

Paper version git-Paper-344 (MC: 1.13.1) (Implementing API version 1.13.1-R0.1-SNAPSHOT)
Citizens version 2.0.24-SNAPSHOT (build 1576)
MobHunting version 6.0.8
BagOfGold version 2.1.1

Thanks,
Gronsten

**Comment by Rocologo** [comment]
You must check your server log for errors when you start the server.

Or show me the log using pastebin if you cant find the error

**Comment by Rocologo** [comment]
No answer... and the code has changed a lot. Newest snapshot is here

https://fractal.lindegaard.one:8181/job/BagOfGold/187/
