### ISSUE TITLE
BagofGold Disappearing on Relog

### ISSUE THREAD

**Issue by CampingSteve** [Rocologo/BagOfGold#44]
When players sell items and receive money....when they disconnect and relog the bag of gold disappears from their inv making their balance 0 .... will run your plugin in debug and see if I can find out why.

**Comment by CampingSteve** [comment]
when running in debug everything works fine....trying to find out what players are doing to wipe the money from their inv....I did it myself once but not in debug...hopefully I can replicate it

**Comment by CampingSteve** [comment]
or the bagofgold isn't saved as in inv item

**Comment by Rocologo** [comment]
When the players logout their balance is saved in the the database, the same should happen if you restart the server. I have tested the along ago, but maybe something is broken.

When a player login, thier inventory is adjusted to the balance. If something has gone wrong and the balance is 0 the inventory will be wiped

**Comment by CampingSteve** [comment]
Whatever is default lol

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by CampingSteve** [comment]
I use inventory restore...so know the bag is in the inv when a player quits....so i can restore their bag....but it seems to not add it back when server starts.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by CampingSteve** [comment]
Banked money isnt affected...and placed down money bags are unaffected.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by Rocologo** [comment]
okay, then you use sqlite. I just tested on MySQL, and restarted the server whilæe I was loggedin, but i didnt loose the money...

**Comment by Rocologo** [comment]
I dont know Inventory restore. Maybe this is the problem?

I would like to see your serverlog from when you do a restart while having a player online to the server is up again and the player logges in again?

**Comment by Rocologo** [comment]
And now i have tested on mys Sqlite test server - no problems.
