### ISSUE TITLE
Bag loses value after going through hopper

### ISSUE THREAD

**Issue by braceyourself07** [Rocologo/BagOfGold#46]
Hey, long time no see.  Since the last round of bug fixes back in September, we haven't had any issues and our players are enjoying the plugin especially with MobHunting.

One player reported recently, however, that he accidentally dropped a bag of money into a hopper and when he got it back out it was a bag of money playerhead but no value associated with it.  Since we haven't had any issues in quite some time, I had debugging turned off.  I can test more thoroughly after the US holidays when I get some time to try to re-create the circumstance on a test server with debug on.

Thanks so much,

Mike

**Comment by Rocologo** [comment]
Hi Mike

I have been very busy at work for quite some time. 

I will keep the ticket open until I have had time to test this
