### ISSUE TITLE
Sign conflicting with other sign plugins

### ISSUE THREAD

**Issue by FabioZumbi12** [Rocologo/BagOfGold#50]
Hi,

I am using the bag of gold, but seems is conflicting with other sign plugins.

As example, Economy bank:
![image](https://user-images.githubusercontent.com/5833818/50577314-e40d8b00-0e0c-11e9-9cc5-558f873fad5c.png)

BagOfGold thinks that sign be your own, see the four line about the error, but the economy sign is created.

The tags is different too! `[Bank]` if of other plugin!

Found this on code: https://github.com/Rocologo/BagOfGold/blob/master/src/one/lindegaard/BagOfGold/bank/BankSign.java#L293

This is not configurable :/

**Comment by Rocologo** [comment]
Hi Fabio

I saw your commits to the source code after I wrote the answer, and I see that there was a conflict. I have added your commits except to the "RewardListeners.java" and "money" in plugin.yml.

Also the changes in the pom.xml gave me problems, when I build the plugin on my Jenkins server

Kind regards
Rocologo

**Comment by Rocologo** [comment]
I got pom.xml working. Please help me testing newest build.
https://fractal.lindegaard.one:8181/job/BagOfGold/

**Comment by FabioZumbi12** [comment]
Sorry, i had to remove BagOfGold of my server because for some reason, all online player moneys has been zeroed :/

I just using MobHunting and seems MH is already dropping bag of golds and we can sell/bey only with MH too.

**Comment by Rocologo** [comment]
Ok, sorry to hear that.
