### ISSUE TITLE
use-bagofgold-as-an-economy-plugin: change to false, what happens

### ISSUE THREAD

**Issue by kelso6969** [Rocologo/BagOfGold#55]
What would happen if I changed this setting back to false

  use-bagofgold-as-an-economy-plugin: true

Would it impact the current balances of people, yes I know currently /bal goes off whats in their inventory, and banked gold is essentials money essentially correct?

Changing that to false would hopefully just make it so /bal shows essentials economy, then they could go bank all the money in chests and inv to get it to max.

Is that right or would this totally screw things up?

**Comment by Rocologo** [comment]
Im not sure if I understand your question. If you dont want BagOfGold as your money you should not install BagOfGold.

**Comment by Rocologo** [comment]
Its not possible to have two economy plugins. Ex BagOfGold and Essentials. Vault would not know where to pick the money when a plugin like AreaShop ask it to. 

The hole idea about BagOfGold is that you need to have the money you want to use in your inventory. If you store the money (bagofgold) in the bank or in a chest. The money is safe. This is the same behavior as other economy plugins which support bank features.

**Comment by kelso6969** [comment]
I understand. 
Which is why i want to set use-bagofgold-as-an-economy-plugin: false, then make people still deposit money from rewards and mobhunting drops to bank.

**Comment by kelso6969** [comment]
this can be closed
