### ISSUE TITLE
convert back to essentials?

### ISSUE THREAD

**Issue by kelso6969** [Rocologo/BagOfGold#56]
The command bagofgold convert bagofgold essentials works, but doesn't seem to populate the userdata/uid.yml file. Is this not meant to work this way and if not can it be added?

**Comment by Rocologo** [comment]
Its unfortunately not something i can do. If userdata is not created its a bug in essentials. I just use the vault API to essentials. Nothing else.

**Comment by kelso6969** [comment]
I wrote a sqlite to mysql converter to dump the data.

I then wrote a PHP script to parse it

$sql = "SELECT * from mh_PlayerSettings";
$result = $conn->query($sql);
while($row = $result->fetch_assoc()) {
    $uuid = $row['UUID'];
    $player = $row['NAME'];
    //echo "$player\n";
    $bank_bal = $conn->query("select BANK_BALANCE as bank_bal from mh_Balance where UUID = '".$uuid."' and GAMEMODE='0'")->fetch_object()->bank_bal;
    echo "$player -> $bank_bal\n";
}

Echo will be replaced with a eco give $player $bank_bal and after I make the change I can paste it in :)

thanks anyway

**Comment by Rocologo** [comment]
Ahh okay

**Comment by kelso6969** [comment]
this can be closed.
