### ISSUE TITLE
Feature request: Hide dropped bag name and/or price

### ISSUE THREAD

**Issue by XxDILBERTxX** [Rocologo/BagOfGold#58]
An option to not show the name and value hovering over the drops.. to make the bags blend in with the other items more

**Comment by Rocologo** [comment]
You are not the only one with this wish, but at the moment this is not possible for technical reasons.

**Comment by Rocologo** [comment]
You can change the DisplayName in BagOfGoldCore.yml

If you dont want a name just write

    skull:

      # This is the displayname format of BagOfGold (SKULL) items.
      displayname_format: ''

But There is one caveat - the Display name in the Inventory will then be "Bag of Gold's head" and Im not able to change that. This is Minecraft standard.

**Comment by Rocologo** [comment]
You can now remove the DisplayName in V8.1.1

See show_displayname in BagOfGoldCore.yml
