### ISSUE TITLE
 water spoils money

### ISSUE THREAD

**Issue by smithy9901** [Rocologo/BagOfGold#59]
When the water washes away the money, they stop being currency
![unknown](https://user-images.githubusercontent.com/37003941/53734601-8261af80-3e95-11e9-8506-673e03b7b1f6.png)

**Comment by Rocologo** [comment]
Please explain the setup? If I drop the bag in the water nothing happens. Water washes away the water? How?

**Comment by Rocologo** [comment]
no answer

**Comment by Darcion** [comment]
pls reopen this, i got this error too. place a bagofgold as item on the ground where water flows and you have your bug.

**Comment by Rocologo** [comment]
thanks for a clear explanation. Will test and fix.

**Comment by Rocologo** [comment]
Fixed in next release which will come soon.

**Comment by Rocologo** [comment]
released
