### ISSUE TITLE
Loss of Bag of Gold on helmet

### ISSUE THREAD

**Issue by Jacxk** [Rocologo/BagOfGold#6]
When I put the bag of gold in the helmet slot after 1 seconds it gets removed and all the money is lost obviously.

**Comment by Rocologo** [comment]
Yes... this is how it works. You can't wear a BagOfGold. So dont try to... :-)

**Comment by Rocologo** [comment]
Ps the money is not lost, it will stay on you balance or dropped next to you depending on your config.yml

**Comment by Rocologo** [comment]
In next release you can wear the mob head rewards, but not the BagOfGold

**Comment by Rocologo** [comment]
This should be fixed in BagOfGOld V0.9.7 and MobHunting V5.3.0
