### ISSUE TITLE
PlaceholderAPI not working

### ISSUE THREAD

**Issue by DefinitlyEvil** [Rocologo/BagOfGold#60]
Hello, 
  It is a very nice plugin, however... placeholders are not working, at all... 

Thank you.

**Comment by Rocologo** [comment]
Sorry to say, but it seems to have never worked... Nobody has tested/used it before.

I have now tested "/papi parse rocologo %bagofgold_balance%" and "/papi parse rocologo %bagofgold_bank_balance%" and they both works now.

This is fixed in release 2.5.4

**Comment by DefinitlyEvil** [comment]
Thanks, that's cool. And I was experiencing some /bal update issues as well. Should it calculate all the money in the inventory in real-time? It looks like you cached it somehow.

**Comment by Rocologo** [comment]
Hmm. The question is no easy to answer :-) BagOfGold is a multi-world economy and and has a balance for both survival and creative, so depending on how, when and where you use the placeholder, you will get different answers. 

Im not saying that there is no bugs :-) but you have to be more specific about the issues, so we can help each other to get this resolved. 

The balances is cached for all online players to deliver good performance, but I dont think this is the problem. It is probably you who is using the placeholder in way I have not thought of, so tell me what you are trying to do with the place holder and then I will try to do the same on my test-server.

**Comment by DefinitlyEvil** [comment]
ah sorry this was another topic about command `/bal`, it seems `/eco set` can't update the balance cache somehow.

**Comment by Rocologo** [comment]
/bal and /eco set is part of essentials, i cant change how they work.  

You have to use /bagofgold commands. Though /bal works fine.

**Comment by Rocologo** [comment]
/bal an /bag money bal should show the same

**Comment by DefinitlyEvil** [comment]
ok thanks, I think you can override those commands or maybe Vault did it for you, because other economy plugins commonly overrode common command names such as /bal or /eco.

**Comment by Rocologo** [comment]
I have decided not to overrule other plugin commands. You should not allow your users to use Essentials Economy commands, if they dont work.
