### ISSUE TITLE
Feature Request: Notifications (Mute/Customization)

### ISSUE THREAD

**Issue by Ramoramparo** [Rocologo/BagOfGold#62]
I am wondering if there is a way to get rid of the notification whenever something occurs related to this plugin? For example, whenever you drop money or find money, it states "You dropped __" or "You found __". You are able to modify in the config which lang file you use, but it seems that the lang files created when the plugin is first loaded are not customizable and have no use. Is the only way to modify them to compile manually based on the source files on github?

Additionally, the command "/bag mute" listed at https://www.spigotmc.org/wiki/bagofgold-commands-permissions/ does not work, as I am assuming it got removed at some point.

**Comment by Rocologo** [comment]
I will will have to dive into this. I will add "/bag mute" as well

**Comment by Rocologo** [comment]
Please help me with the testing using this snapshot

https://fractal.lindegaard.one:8181/job/BagOfGold/225/

**Comment by Ramoramparo** [comment]
Seems to work as intended. Whenever the mute notification goes through however, it says "BagOfG0ld is now muted" instead of "BagOfGold". 

What are the permissions for this (for a permission editor)? 

Anyway to make this a config setting to mute notifications completely or for certain actions (such as dropping/finding money)?

**Comment by Rocologo** [comment]
Sorry for the late response

The typo is fixed in my lang files, but you will have to regerate the file yourself or change the spelling.

The permission is "bagofgold.mute"

Mute should remove all messages from **the player chat** (all messages from BagOfGold).

**Comment by Rocologo** [comment]
fixed in v2.5.8. I hope :-)
