### ISSUE TITLE
Nice plugin

### ISSUE THREAD

**Issue by lvavila** [Rocologo/BagOfGold#63]
Evaluating your plug-in over Gringotts as you seem motivated and current.  Great job.  A few requests:
- bank commands ie /bag bank withdraw 100
- interest of money in the bank using user defined interval (say 15min/.02% accrue)
- is there cash overflow?  Meaning if something is sold via ChestShop and player does not have funds in inventory but does in bank, will it go through?  Or if a player if offline and another buys from his store, what happens?

I very much like the idea of a separate item as currency (bag of gold).  Thank you.

**Comment by Rocologo** [comment]
Hi,

To be honest my dev time is limited at the moment, but I try to keep my plugin updated. I noticed that the Minecraft 1.14-pre5 was released today, so it is important to add the new mobs as fast as possible. 

The intention with BagOfGold is that you must think of the money as physically items (A bag with gold coins) and you can use these money like if it were coins. This means that you have to hide the money in a locked chest if you dont want to loose the money, or you will have to actually go to the Bank-keeper / Bank (signs) to store your gold coins in the bank. 

Its not a creditcard where you can post money electronically. So to say :-) 

This is the reason why the player cant use a "/bag bank withdraw 100" command - that would be a kind of cheating. 

It is for the same reason that there is no "cash overflow" where money goes from the bank. That would be a kind of cheating too. :-) The player will have to GO to the bank keeper / Bank (signs) and the the money they have stored. 

If there were an overflow feature the player would always put all their money in the bank, not to loose the money, if the die or get robbed. That does not make sense.

I will think about making an interest of the money stored in the bank. I might be able to make a simple solution. (not bank accurate), where you can set the interest and how often it is calculated. I dont want to make a solution were I calculate the interest the same way the banks do.

Kind regards 
Rocologo

**Comment by lvavila** [comment]
Big thanks for your reply and comments. As a fellow .net developer I get
it, it's your product and vision.  But being a game server I might think
its up to the server admin to determine what feature is a cheat and not
giving them the config choices I've inquired about.  That is not to say I
don't agree with you. Its just my humble opinion.

My workaround will be to enable the Backpack plugin with "keep on die"
enabled where your bag of gold will reside for each player.  For good or
bad, that is simply a feature my my small player population likes when
using physical economy.  I'm sure we are in the minority.

One observation, when doing a /bag money pay 100 <player>, can you send the
recipient a notification the payment was made.  I think today, it does not.

One final comment, I'm hoping your offering works in 1.14 even without the
new mod additions as mob kill for me is not a feature needed with "Job
Revived" plugin taking care of that. I find it interesting you have that
integrated but on a server lightly loaded with plugins, it make sense.

Again, good work on your plugin.

Regards,

----
*Louie Avila*

**Comment by Rocologo** [comment]
Messages when using "pay" command will is added in next release.

I have not started on the rest yet.

**Comment by lvavila** [comment]
update appreciated

**Comment by Rocologo** [comment]
So I have started to make some basic functions to calculate an interest of the money in the bank. But i have some questions and would like to hear your opinion?

1) Should i user Minecraft time or real time? 
.... I think Minecraft Time is best (https://minecraft.gamepedia.com/Day-night_cycle) this means that 1 Minecraft day is 20 min. If interest is calculated every Minecraft day, it will be calculated every 20 min, every Minecraft week ~ 2.3 hours, every month ~10 hours 
2) How often should the interest be calculated? I think i will make if configurable. Every Minecraft day,  every Minecraft week, every Minecraft month, every Minecraft year.
3) What about passive players? A player logon to the server one time, but never again, that would start the interest calculation, and would continue forever unless i do something about passive players.
4) Should the interest be calculated for all online players or active offlinePlayers as well? Maybe I should calculate the interest each time a player logon for the past periods.

**Comment by lvavila** [comment]
At movies so I’ll keep it short

1 I’d use real time for clock as game cycle is not trackable with analytics like Plan plugin
2 I’d use admin configurable ie 15 min, 60 min etc

3 for passive, if an above cycle is not met, cancel and restart upon new login. No need to store state. 

4 no offline interest. Players get rewarded for being online. 

5. I’d at a max interest cap as a global option (admin config setting). If balance in bank bal is > 10000 or > 100000 then no more interest. That keeps player from becoming op. 

6 a consideration. Players that are afk while online ( all night long) cause issues with accruing interest. I have no answer for this except #5 above. Thoughts?

I appreciate having a voice. 

Louie

**Comment by Rocologo** [comment]
I see this more like a bonus for being online - not an interest calculation. But this could be okay.

I need to find a solution to the AFK problem, a max interest cap is not a good solution. I think.

**Comment by Rocologo** [comment]
PS. I use the plugin "ontime" for this. It cant calculate interest on the bank balance, but it can reward the players for being online. This is what I do.

**Comment by lvavila** [comment]
The concern is once a player hits 1,000,000 (for example), Interest at .20%
becomes a little unbalanced (where the player loses interest in playing).
I literally use a bank plugin now in my 1.13.2 server and I had to shut it
down for this reason.

If we have an option to set a cap ("-1" for no cap) to say 100,000, this
helps new players to get ahead for playing and caps the older players from
getting too rich.  But again , let the admins decide.

Regards,

----
*Louie Avila*

**Comment by lvavila** [comment]
Yup.  Just name it interest though based on what is deposited into the
bank. :)  There is already plugins for "just being online".  I personally
don't use those.

Regards,

----
*Louie Avila*

**Comment by Rocologo** [comment]
it is rather easy to make a cap on the interest, but I still need to find a way to calculate or determine non-AFK time to use for the interest calculation. 

Im think about looking into other plugins like Essentials to see if I can get from there. I dont know other easy ways to get the non-AFK time.

**Comment by lvavila** [comment]
Curious,  is there a “is player moving” check you can do?  Otherwise I would worry about it. Other plugins may be able to deal with player afk. I’m playing with two now. 

Louie

**Comment by Rocologo** [comment]
Yes, Thee is a moving event to catch, but many others which probably needs to be taken care of. I think Essentials sourcecode is public, so I might be able to found out who they do the afk tracking.

**Comment by Rocologo** [comment]
I have had time to study Essentials sourcecode, but this is not easy to calculate "Active time"...

**Comment by Rocologo** [comment]
I have found this Bank plugin which seems to ONLY calculate an interest for onlineplayers. 

Still I dont know if it looks at AFK too...

https://www.spigotmc.org/resources/economy-bank.7674/

**Comment by Rocologo** [comment]
Now I found the Source code. It seems not to look at AFK. :-( 

https://www.spigotmc.org/resources/economy-bank.7674/

**Comment by lvavila** [comment]
This is the one I use. Love it but had to shut down as rich got too rich and economy got lob sided with players in the millions. Talking to that developer too to see about adding interest balance max setting. 

Louie

**Comment by lvavila** [comment]
Ok. I purchased AntiAfkPlus and it works for all types of afk. He also offers play time interest with a setting to stop accruing if player is afk after an admin define time. 

$5 purchase. The afk and reward is not static event, he let’s admit no use op commands using timers.

Example
120 = 2min 
Command: chat <player> you’ve been online 2 minutes
Command: eco <player> add 100 # $100 added to player

Same with afk detection. After time has been passed...
Send message then issue logout command to player. Since it’s all command, you can warp player instead of logout player. Interesting technique. 

Louie

**Comment by lvavila** [comment]
To give you ideas for future projects although I don't know how he detect
events afk: and playtime:, here is his config using my settings.  I have
playtime: commented out.

  afk:
    6300: #120 seconds = 2 minutes
      -  "MESSAGE|&eAFK &7» &cYou have been AFK for two minutes, you will
be kicked soon!"
      -  "TITLE|&6You have been ; &6AFK for 105 minutes"
    7195:
      -  "TITLE|&6Anti AFK ; &bYou will be kicked in &c5 &bseconds"
    7196:
      -  "TITLE|&6Anti AFK ; &bYou will be kicked in &c4 &bseconds"
    7197:
      -  "TITLE|&6Anti AFK ; &bYou will be kicked in &c3 &bseconds"
    7198:
      -  "TITLE|&6Anti AFK ; &bYou will be kicked in &c2 &bseconds"
    7199:
      -  "TITLE|&6Anti AFK ; &bYou will be kicked in &c1 &bsecond"
    7200: #300 seconds = 5 minutes
      -  "COMMAND|kick %PLAYER% You have been kicked as you have been AFK
for 120 minutes"
#
## Actions that are executed when the player plays for a certain time
(store_player_time needs to be enabled for this)
#
  playtime:
    #300: #300 seconds = 5 minutes
    #  -  "MESSAGE|&ePlayTime &7» &cYou have played for 5 Minutes! &6You
have been rewarded with $100!"
    #  -  "COMMAND|eco give %PLAYER% 100"
    #3600: #3600 seconds = 1 hour
    #  -  "MESSAGE|&ePlayTime &7» &cYou have played for 1 hour! &6You have
been rewarded with $1000!"
    #  -  "COMMAND|eco give %PLAYER% 1000"
    #86400: #86400 seconds = 1 day
    #  -  "MESSAGE|&ePlayTime &7» &cYou have played for 1 day - Wow, you
really like this server! &6You have been rewarded with $10000!"
    #  -  "COMMAND|eco give %PLAYER% 10000"
    #600%: # -- PUTTING A % AFTER A NUMBER MEANS IT WILL BE REPEATED EVERY
X SECONDS
    #  -  "MESSAGE|&eAFK &7» &cYou have been rewarded with $100 for
playing! "
    #  -  "COMMAND|eco give %PLAYER% 100"
Regards,

----
*Louie Avila*

**Comment by Rocologo** [comment]
It now possible to get interest of the money in the bank (default disabled) but I still not have a solution for not counting time when a player goes afk.

**Comment by Rocologo** [comment]
I will not work more on this one, unless you find an bug. If you do so, please make a new ticket.
