### ISSUE TITLE
Gringotts version of money does not work with banks

### ISSUE THREAD

**Issue by Wolfability** [Rocologo/BagOfGold#66]
I switched over to the gringotts settings and banks will not allow you to deposit with them. I left the emeralds as default. I could only get them deposited by clicking the sign with the original bagofgold head. The head converted into emeralds though seemingly randomly. I am using version 2.6.1 on MC 1.14. I do not have Protocol lib or PerworldInventory installed.

**Comment by Rocologo** [comment]
this is is fixed in next release 2.7.2

**Comment by Rocologo** [comment]
2.7.2 released
