### ISSUE TITLE
Duping Bug

### ISSUE THREAD

**Issue by Regnak85** [Rocologo/BagOfGold#70]
Player has full Inventory, and one BagOfGold.
Then he tried to pickup another bag.

This happend...

![Gold](https://user-images.githubusercontent.com/1340357/63063618-aa057b00-befd-11e9-9f37-3f0d66575b6e.jpg)

**Comment by GummiBoat** [comment]
Tested around and found this; since it's possibly connected I posted it here. I'll open a separate Issue if it isn't: https://imgur.com/1K5o7Hs

**Comment by Rocologo** [comment]
it should be fixed in newest version
