### ISSUE TITLE
tables in mh_balance disappear after switching servers or restart of bungeecord servers

### ISSUE THREAD

**Issue by Darcion** [Rocologo/BagOfGold#72]
our bungeecord system tries to use your bank system, we use mysql to get everything work under our subservers. when we transfer money to the bank, it works for some time but after some time or server restart the bank_balance or the whole row disappears.

i am this one:

![grafik](https://user-images.githubusercontent.com/1327512/63491945-c6368880-c4b8-11e9-9e29-daefbcdffb50.png)

now i transfered some money to then bank:

![grafik](https://user-images.githubusercontent.com/1327512/63492158-24fc0200-c4b9-11e9-9097-9d0edb364950.png)

i switched to one of the subserver but everything is ok, now i restarted two of the subservers (on both we have the bank)

![grafik](https://user-images.githubusercontent.com/1327512/63492891-ae600400-c4ba-11e9-816a-8971944bb7f4.png)

the whole entry is gone but when i connect the money in my poket is still there (saved from another plugin mysqlinventorybridge)

![grafik](https://user-images.githubusercontent.com/1327512/63493016-eebf8200-c4ba-11e9-8a86-068dbb3bf53b.png)

i switched the slots of the money in my inventar and the entry for this is back but bank is empty

![grafik](https://user-images.githubusercontent.com/1327512/63493116-275f5b80-c4bb-11e9-9b34-30f45054cfa9.png)

what i cannot understand are the other 3 rows. next test is my account without admin(wildcards in permission) and without op.

![grafik](https://user-images.githubusercontent.com/1327512/63493453-ec115c80-c4bb-11e9-8d83-bc9a563d0c37.png)

now i left the server on another subserver and my row is missing:

![grafik](https://user-images.githubusercontent.com/1327512/63493559-309cf800-c4bc-11e9-83ce-02f27cbcd578.png)

but without this row, i got my money back from the bank...

![grafik](https://user-images.githubusercontent.com/1327512/63493728-7bb70b00-c4bc-11e9-8738-d69caa9e8144.png)

![grafik](https://user-images.githubusercontent.com/1327512/63493755-8a9dbd80-c4bc-11e9-9c42-13669b8c886e.png)

now i transfered money to the bank and left the server (i did not switched to another subserver)

![grafik](https://user-images.githubusercontent.com/1327512/63493882-d9e3ee00-c4bc-11e9-99cc-e9db0840ed48.png)

i restared this one subserver only and everything is ok
after restarted of the other subserver everything is ok

now i booted both subserver at the same time and its missing again:

![grafik](https://user-images.githubusercontent.com/1327512/63494321-ba999080-c4bd-11e9-8935-5d784af8ef58.png)

bank is empty... and i have money in my inventar (saved from the other plugin) but when i try to use deposit on the sign it does not recognize the money in my hand

![grafik](https://user-images.githubusercontent.com/1327512/63494519-20861800-c4be-11e9-80b1-e7e7ee143841.png)

because the database for my account is empty. 

![grafik](https://user-images.githubusercontent.com/1327512/63494542-31368e00-c4be-11e9-9a25-8d7e92f67dd9.png)

now i switch slots for the money item in my inventar to get the entry back for me.

![grafik](https://user-images.githubusercontent.com/1327512/63494609-588d5b00-c4be-11e9-9fda-947abaa9583f.png)

now i switched subservers but the whole table is missing...

![grafik](https://user-images.githubusercontent.com/1327512/63494738-a0ac7d80-c4be-11e9-8855-d754f3636f8e.png)

but the bank is still recognize the money in my inventar...

![grafik](https://user-images.githubusercontent.com/1327512/63494806-c76ab400-c4be-11e9-90d0-28a28186cce9.png)

table is back

![grafik](https://user-images.githubusercontent.com/1327512/63494821-d5203980-c4be-11e9-883c-763462d550b1.png)

switching server and its gone again:

![grafik](https://user-images.githubusercontent.com/1327512/63494977-33e5b300-c4bf-11e9-9e56-30b9bc563a25.png)

going back to the first subserver its back again...

![grafik](https://user-images.githubusercontent.com/1327512/63496218-ca1ad880-c4c1-11e9-9a77-6ebeb549b935.png)

i cant see the problem, all settings are identical on every subserver. the mysql log does not prevent any interesting log:

```
/* 2019-08-22 09:28:54 [fablecraft] */ /* Ping server ... */
/* 2019-08-22 09:28:54 [fablecraft] */ /* Ping server ... */
/* 2019-08-22 09:28:54 [fablecraft] */ SELECT * FROM `minecraft`.`mh_Balance` LIMIT 1000;
/* 2019-08-22 09:28:54 [fablecraft] */ /* Result #1 fetched. */
/* 2019-08-22 09:28:54 [fablecraft] */ /* Detected column type for UUID: CHAR */
/* 2019-08-22 09:28:54 [fablecraft] */ /* Detected column type for WORLDGRP: VARCHAR */
/* 2019-08-22 09:28:54 [fablecraft] */ /* Detected column type for GAMEMODE: INT */
/* 2019-08-22 09:28:54 [fablecraft] */ /* Detected column type for BALANCE: DOUBLE */
/* 2019-08-22 09:28:54 [fablecraft] */ /* Detected column type for BALANCE_CHANGES: DOUBLE */
/* 2019-08-22 09:28:54 [fablecraft] */ /* Detected column type for BANK_BALANCE: DOUBLE */
/* 2019-08-22 09:28:54 [fablecraft] */ /* Detected column type for BANK_BALANCE_CHANGES: DOUBLE */
/* 2019-08-22 09:28:54 [fablecraft] */ /* Ping server ... */
/* 2019-08-22 09:28:54 [fablecraft] */ SHOW CREATE TABLE `minecraft`.`mh_Balance`;
/* 2019-08-22 09:28:54 [fablecraft] */ /* Result #1 fetched. */
/* 2019-08-22 09:28:54 [fablecraft] */ /* Detected column type for Table: VARCHAR */
/* 2019-08-22 09:28:54 [fablecraft] */ /* Detected column type for Create Table: VARCHAR */
/* 2019-08-22 09:28:54 [fablecraft] */ /* Ping server ... */
/* 2019-08-22 09:28:54 [fablecraft] */ /* Fetching list of collations ... */
/* 2019-08-22 09:28:54 [fablecraft] */ /* Ping server ... 
```

databasesetting:

database:
  type: mysql
  username: mc
  password: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  host: localhost:3306
  database: minecraft?useSSL=false&?autoReconnect=true
  database_version: 2

for every subserver we use symlinks to provide the same files and folders.

can you check if bungeecord made this plugin useless?

**Comment by Darcion** [comment]
maybe you can look into this: https://www.spigotmc.org/threads/bungeecord-async-mysql-updating-problem.334878/

**Comment by Darcion** [comment]
i switched to another plugin "aconomy" and now i have no problems anymore.

**Comment by Rocologo** [comment]
I checked the link and after reading this, I can see that BagOfGold has a problem, when a player leaves a server and joins another server. 

I high likely that the balance on the SQL server has not been updated when the player enters 
another server. And this will break the balance. I will have to think about how this can be solves.

Usually i only update the balances in the database every 15 min not to make lag. Ill see if I can come up with a solution.

**Comment by Rocologo** [comment]
Are you still interested in using BagOfGold on a Bungee network with a shared SQL server? I could disable the cache to let you test if the cache is really needed?
