### ISSUE TITLE
EntityPickupItemEvent - Java Error

### ISSUE THREAD

**Issue by JohnBeres1** [Rocologo/BagOfGold#76]
Hello,

I just installed your mod and all seems to be working. The only part that concerns me is an error when I go to pick up a bag of gold (every time) my console gets flooded with Java errors. Do you have any idea what the culprit may be?

Spigot Version: 1.14.4
Java: JRE v8 Update 122 (x64)
BagOfGold Version: 2.8.3

[Screenshot Of Errors](https://imgur.com/a/lQEHQ0P)

Thank-you! ^ _ ^

**Comment by Rocologo** [comment]
Og looks like ProtocilLib need to be updated?



Sendt fra Samsung Galaxy S10+


-------- Oprindelig besked --------
Fra: John-MB <notifications@github.com>
Dato: 06/10/2019 03.21 (GMT+01:00)
Til: Rocologo/BagOfGold <BagOfGold@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Emne: [Rocologo/BagOfGold] EntityPickupItemEvent - Java Error (#76)


Hello,

I just installed your mod and all seems to be working. The only part that concerns me is an error when I go to pick up a bag of gold (every time) my console gets flooded with Java errors. Do you have any idea what the culprit may be?

Spigot Version: 1.14.4
Java: JRE v8 Update 122 (x64)
BagOfGold Version: 2.8.3

Screenshot Of Errors<https://imgur.com/a/lQEHQ0P>

Thank-you! ^ _ ^

**Comment by JohnBeres1** [comment]
That was the issue. Good catch! Thank-you, and feel free to close.

**Comment by Rocologo** [comment]
Your welcome
