### ISSUE TITLE
Bag Breaks

### ISSUE THREAD

**Issue by Goatii** [Rocologo/BagOfGold#77]
If the bag is placed and then broken by something other than a player (water, a piston etc), then it breaks as a playerhead and no longer works.

**Comment by Rocologo** [comment]
Are you on Version 2.8.6?

Please give me ONE test senario, which I can test on my test-server?

**Comment by Goatii** [comment]
I am.

I place the bag head underwater, and it turns into a normal head called 'BagOfGold's Head'. 
I place the bag head and then push it with a pistion, and it turns into a normal head called 'BagOfGold's Head'. 

Those are the only two I've tested

**Comment by Rocologo** [comment]
Thank you. You see I was wise that I asked. I have never tried to place one of the bags underwater. I have an area on my test-server where I test what happens when another block breaks the head. I will need to add a new test now :-)

**Comment by Rocologo** [comment]
This works in V3.0.3
