### ISSUE TITLE
Feature Request: Lock bag

### ISSUE THREAD

**Issue by Goatii** [Rocologo/BagOfGold#78]
I'd like a feature that would lock the bag in a slot, and then even if you have 0 money, it'd stay in that slot. It would be undroppable, unmovable and wouldn't drop on death. Preferably, the slot of the bag would be adjustable in the config.

**Comment by Rocologo** [comment]
I have actually thought about this feature myself. 

I know it sound simple, but actually it makes the plugin even more complex.

It the monent I dont have the time to fullfill this request, but I will keep the ticket open, and may be look at it at later. 

You are the first one who contacts me about this idea.

**Comment by Goatii** [comment]
- [ ] I've also got another suggestion, but don't want to open another ticket - allow players to fully customize the bag name when dropped and in inventory. For example, when dropped, the bag name would be $money and when in inventory the bag name could be Money Bag: $money. I'm running into an issue where if I change the  drop-money-on-ground-skull-reward-name: to just $, the bag still shows $ (money).

**Comment by Goatii** [comment]
for the locked bag, couldn't you just cancel InventoryClickEvent, PlayerSwapHandItemsEvent and PlayerDropItemEvent? And on EntityPickupItemEvent, just get the money in the name of the bag and add it to the bag that would be locked in the player's slot?

**Comment by Rocologo** [comment]
Im sorry. I have decided not to make this. It sounds like you can do some development? :-) True that I could handle this in the named events (and some more) but I already use these events and there are pretty complex. I don't want to add more complexity for now. Its more important to me that the plugin is stable.
