### ISSUE TITLE
Feature Request: Customise Name

### ISSUE THREAD

**Issue by Goatii** [Rocologo/BagOfGold#79]
Allow players to fully customize the bag name when dropped and in inventory. For example, when dropped, the bag name would be $money and when in inventory the bag name could be Money Bag: $money. I'm running into an issue where if I change the drop-money-on-ground-skull-reward-name: to just $, the bag still shows $ (money) rather than $money.

Ideally, this would be done with a <money> variable, which would represent the money the player is carrying in the bag.

**Comment by Rocologo** [comment]
Im not sure about  what you want to achieve? 

Do you only want to show a number instead of the number and the name? 

IE. "10" instead of "10 BagOfGold"

**Comment by Rocologo** [comment]
Please check ticket #95

**Comment by Rocologo** [comment]
You can change the displayname / format in newest snapshot, bur please backup first.
