### ISSUE TITLE
Banker

### ISSUE THREAD

**Issue by Goatii** [Rocologo/BagOfGold#80]
The banker only works on SpigotMC servers.

To avoid this, a command could be added to withdraw or deposit money in the bank, so that the process could be accomplished through the use of other NPC plugins - /bog bank deposit (player) (amount) and /bog bank withdraw (player) (amount) and if the amount was left blank then it would withdraw/deposit all

**Comment by Rocologo** [comment]
No, its not the NPC which is the problem. I use a Spigot feature. Click-able chat events.

**Comment by Rocologo** [comment]
no answer
