### ISSUE TITLE
Spectator mode duplication bug.

### ISSUE THREAD

**Issue by En0tS** [Rocologo/BagOfGold#83]
Tested on 2.8.6 with paperspigot (final build 1.12.2).

If player have balance in spectator mode and doesn't bag of gold in inventory, he will drop bag with spectator balance when entering in spectator mode.
![image](https://user-images.githubusercontent.com/36606833/68539550-2e955780-038e-11ea-9cc0-995cfa7158ee.png)
![image](https://user-images.githubusercontent.com/36606833/68539551-3228de80-038e-11ea-8b79-e9baba544868.png)

So you can dupe a lot of money just switching from creative/survival/adventure to spectator mode again and again, cause spectator balance does not change when it happens.

**Comment by Rocologo** [comment]
Please help me testing newest build: 

https://fractal.lindegaard.one:8181/job/BagOfGold/

(Build 376 or newer)
