### ISSUE TITLE
[IMPORTANT] Gold item duping issue.

### ISSUE THREAD

**Issue by FourNineRugz** [Rocologo/BagOfGold#86]
With a full inventory, when you shift-click a gold head into your equipment slot and close out of it, the gold duplicates. I am on version 2.9.0

**Comment by Rocologo** [comment]
Hi all. My development environment has been broken and I did not have to to fix it. but TODAY i got it fixed and I can try to remove the most important bugs 

Please help me with the testing
https://fractal.lindegaard.one:8181/job/MobHunting/
https://fractal.lindegaard.one:8181/job/BagOfGold/

**Comment by Rocologo** [comment]
Fixed in 7.0.1
