### ISSUE TITLE
Reward Head (Bag too) Hidden Text.

### ISSUE THREAD

**Issue by mvp-dev** [Rocologo/BagOfGold#89]
![2020-03-30_04 27 09](https://user-images.githubusercontent.com/39757583/77897067-c82aac00-723e-11ea-81b2-f28bc09b8b24.png)
I get purple text when hovering over both of your mobhunting and bagofgold plugins.
This causes the important information to go off the screen. It does this regardless of permissions and op status.

It means I cannot see the worth of the bags of gold when hovering over them.

**Comment by Rocologo** [comment]
You need to install ProtocolLib to remove this text.
