### ISSUE TITLE
BagOfGold Bank sign not working

### ISSUE THREAD

**Issue by coph1563** [Rocologo/BagOfGold#91]
not only does the custom name for the bank not work but the signs wont even create without error saying "Line 2 must be deposit,withdrawal or balance" 
which it does...

**Comment by Rocologo** [comment]
You need to give me more information. I have just tested the feature using "MyBank" and it works fine, so you need to explain what you have done? Also do you get any errors in the console?

![image](https://user-images.githubusercontent.com/1008133/78469356-9aeb6b80-7720-11ea-988c-c692ddc58c08.png)

**Comment by coph1563** [comment]
https://youtu.be/BZ8WvTbBBRw

**Comment by Rocologo** [comment]
Strange. Its working perfectly when I change them name.

let me see your lang file, so I can match the translations. Also you should check if there is any spaces after the bank name in the config.yml ?

**Comment by Rocologo** [comment]
no answer
