### ISSUE TITLE
Picking up gold doesn't add it to player's inventory

### ISSUE THREAD

**Issue by Feikovandijk** [Rocologo/BagOfGold#98]
Hia,
I just installed your plugin on my 1.15.2 Paper server and so far its been working great, but sadly some of my players have had some issues where when they place the bag on the ground and break it, it looks like the bag is picked up but is not added to the player's inventory.

05.05 20:24:45 [Server] INFO [BagOfGold] [Debug] Player placed a reward block: {Description=Gold, money=100.00000}
05.05 20:24:45 [Server] INFO [BagOfGold] [Debug] Removing 100 from Player's balance 100
05.05 20:24:47 [Server] INFO [BagOfGold] [Debug] A SKULL(100) was dropped on the ground as item SKULL (# of rewards=1)(3)
05.05 20:24:48 [Server] INFO [BagOfGold] [Debug] Player picked up a Gold (# of rewards left=0)

Am I missing anything here?

**Comment by Rocologo** [comment]
Could you please test  newest snapshot on my jenkins server?

**Comment by Feikovandijk** [comment]
That seems to have fixed it, thank you!
