### ISSUE TITLE
Slimefun's Gold dust getting deleted

### ISSUE THREAD

**Issue by Feikovandijk** [Rocologo/BagOfGold#99]
Hia, 
Again thank you for creating the plugin, so far it's been amazing.
I run a server with the Slimefun4 plugin installed, this plugin adds an item called Gold Dust. Sadly when this item enters a player's inventory it seems like BagOfGold deletes it, thinking its a gold bag. Would it be possible to fix this by changing the name of the BagOfGold or using another simple fix?
Thanks in advance!

**Comment by Rocologo** [comment]
Why do you think it is the BagOfGold plugin which deleted the Gold dust item? Do you get any messages in the server log when this happens?

**Comment by Feikovandijk** [comment]
The player gets a message when they move or pick up a gold dust item: 
![image](https://user-images.githubusercontent.com/10695341/81315857-20996880-908b-11ea-8620-fb20482339ad.png)

**Comment by Rocologo** [comment]
This can can only happen if the two items has the same display name? So have you renamed the BagOfGold item to the same name as the other plugin uses? "Gold dust" or sometning? 

The two plugins can not use the same name for the items, because the are not the same.

**Comment by Feikovandijk** [comment]
Wow, that was a very clever fix. Changing the name from 'Gold coins' to 'Coins' fixed all issues.

**Comment by Rocologo** [comment]
Yes. I think i will mention this in the config.yml
